Repository Flank/flank-dashboard, pull requests merged in 2020-12, with the labels that each got.

#843 feat: Implement tooltip popup
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/tooltip_icon/widgets/tooltip_icon.dart
  metrics/web/lib/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data.dart
  metrics/web/lib/common/presentation/tooltip_popup/widgets/tooltip_popup.dart
  metrics/web/lib/common/presentation/widgets/tooltip_title.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_title_header.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/common/presentation/tooltip_icon/widgets/tooltip_icon_test.dart
  metrics/web/test/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data_test.dart
  metrics/web/test/common/presentation/tooltip_popup/widgets/tooltip_popup_test.dart
  metrics/web/test/common/presentation/widgets/tooltip_title_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_title_header_test.dart
  metrics/web/web/icons/Info.svg
Labels: size/XXL

#858 fix: Rename info icon
  metrics/web/web/icons/info.svg
Labels: Snake 🐍

#859 feat: Improve CI Integrations error handling
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/cli/error/sync_error.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/error/sync_error_test.dart
  metrics/ci_integrations/test/test_utils/matcher_util.dart
Labels: Snake 🐍, size/M

#860 fix: Fix SyncError test group name
  metrics/ci_integrations/test/cli/error/sync_error_test.dart
Labels: Snake 🐍, size/XS

#856 docs: Update Instant Config design
  metrics/web/docs/features/instant_config/01_instant_config_design.md
  metrics/web/docs/features/instant_config/diagrams/instant_config_data_layer_class_diagram.puml
  metrics/web/docs/features/instant_config/diagrams/instant_config_domain_layer_class_diagram.puml
  metrics/web/docs/features/instant_config/diagrams/instant_config_presentation_layer_class_diagram.puml
  metrics/web/docs/features/instant_config/diagrams/instant_config_sequence_diagram.puml
  metrics/web/docs/features/remote_config/01_remote_config_design.md
  metrics/web/docs/features/remote_config/diagrams/remote_config_data_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_domain_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_presentation_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_sequence_diagram.puml
Labels: size/XL

#863 feat: Improve base graphs documentation
  metrics/web/lib/base/presentation/graphs/bar_graph.dart
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
  metrics/web/lib/base/presentation/graphs/sparkline_graph.dart
Labels: Snake 🐍, size/M

#861 feat: Add Metrics Web Jenkins ci integrations config
  .metrics/jenkins/metrics_web_config.yml
Labels: size/S

#864 fix: Fix typo in Metrics Web config
  .metrics/jenkins/metrics_web_config.yml
Labels: Snake 🐍, size/XS

#862 feat: Implement domain layer for Instant Config feature
  metrics/web/lib/common/domain/entities/instant_config.dart
  metrics/web/lib/common/domain/repositories/instant_config_repository.dart
  metrics/web/lib/common/domain/usecases/fetch_instant_config_usecase.dart
  metrics/web/lib/common/domain/usecases/parameters/instant_config_param.dart
  metrics/web/test/common/domain/entities/instant_config_test.dart
  metrics/web/test/common/domain/usecases/fetch_instant_config_usecase_test.dart
  metrics/web/test/common/domain/usecases/parameters/instant_config_param_test.dart
Labels: size/L

#867 feat: Configure Coverage Converter and CI Integrations builds import from Jenkins
  .metrics/jenkins/ci_integrations_config.yml
  .metrics/jenkins/coverage_converter_config.yml
Labels: size/S

#857 feat: Implement Firebase Analytics Data layer
  docs/16_dependencies_licenses.md
  metrics/web/lib/analytics/data/repositories/firebase_analytics_repository.dart
  metrics/web/lib/analytics/domain/repositories/analytics_repository.dart
  metrics/web/lib/analytics/domain/usecases/log_login_use_case.dart
  metrics/web/lib/analytics/domain/usecases/reset_user_use_case.dart
  metrics/web/pubspec.yaml
  metrics/web/test/analytics/domain/usecases/log_login_use_case_test.dart
  metrics/web/test/analytics/domain/usecases/reset_user_use_case_test.dart
  metrics/web/web/index.html
Labels: size/L

#868 feat: Instant config data layer
  metrics/web/lib/common/data/model/instant_config_data.dart
  metrics/web/lib/common/data/repositories/firestore_instant_config_repository.dart
  metrics/web/lib/common/domain/entities/instant_config.dart
  metrics/web/test/common/data/model/instant_config_data_test.dart
  metrics/web/test/common/domain/usecases/fetch_instant_config_usecase_test.dart
Labels: size/L

#870 feat: Instant Config Firestore rules
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/instant-config-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: size/L

#865 docs: Create Buildkite Integration document
  docs/17_buildkite_ci_integration.md
  docs/diagrams/buildkite_sync_sequence_diagram.puml
Labels: size/L

#871 feat: Implement Firebase Analytics Presentation layer
  metrics/web/lib/analytics/domain/usecases/parameters/page_name_param.dart
  metrics/web/lib/analytics/presentation/state/analytics_notifier.dart
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/domain/usecases/parameters/user_id_param.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/routes/observers/firebase_analytics_observer.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/lib/main.dart
  metrics/web/test/analytics/presentation/state/analytics_notifier_test.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/common/presentation/routes/observers/firebase_analytics_observer_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/test_utils/analytics_notifier_mock.dart
  metrics/web/test/test_utils/analytics_notifier_stub.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/XL

#874 feat: Instant Config - Presentation layer
  metrics/web/lib/auth/presentation/pages/loading_page.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/instant_config/presentation/state/instant_config_notifier.dart
  metrics/web/lib/instant_config/presentation/view_models/fps_monitor_instant_config_view_model.dart
  metrics/web/lib/instant_config/presentation/view_models/instant_config_view_model.dart
  metrics/web/lib/instant_config/presentation/view_models/login_form_instant_config_view_model.dart
  metrics/web/lib/instant_config/presentation/view_models/renderer_display_instant_config_view_model.dart
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/instant_config/presentation/state/instant_config_notifier_test.dart
  metrics/web/test/instant_config/presentation/view_models/fps_monitor_instant_config_view_model_test.dart
  metrics/web/test/instant_config/presentation/view_models/login_form_instant_config_view_model_test.dart
  metrics/web/test/instant_config/presentation/view_models/renderer_display_instant_config_view_model_test.dart
  metrics/web/test/test_utils/auth_notifier_mock.dart
  metrics/web/test/test_utils/instant_config_notifier_mock.dart
  metrics/web/test/test_utils/instant_config_notifier_stub.dart
  metrics/web/test/test_utils/matcher_util.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/XL

#878 fix: Move Data and Domain layers to a separate instant_config folder
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/instant_config/data/model/instant_config_data.dart
  metrics/web/lib/instant_config/data/repositories/firestore_instant_config_repository.dart
  metrics/web/lib/instant_config/domain/entities/instant_config.dart
  metrics/web/lib/instant_config/domain/repositories/instant_config_repository.dart
  metrics/web/lib/instant_config/domain/usecases/fetch_instant_config_usecase.dart
  metrics/web/lib/instant_config/domain/usecases/parameters/instant_config_param.dart
  metrics/web/lib/instant_config/presentation/state/instant_config_notifier.dart
  metrics/web/test/instant_config/data/model/instant_config_data_test.dart
  metrics/web/test/instant_config/domain/entities/instant_config_test.dart
  metrics/web/test/instant_config/domain/usecases/fetch_instant_config_usecase_test.dart
  metrics/web/test/instant_config/domain/usecases/parameters/instant_config_param_test.dart
  metrics/web/test/instant_config/presentation/state/instant_config_notifier_test.dart
Labels: Snake 🐍

#877 feat: Implement initial routes generation
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/lib/common/presentation/routes/observers/firebase_analytics_route_observer.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/lib/main.dart
  metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/common/presentation/routes/observers/firebase_analytics_route_observer_test.dart
Labels: size/M

#879 feat: Toggle Login Form with Instant Config
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/password_sign_in_option.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/auth/presentation/widgets/password_sign_in_option_test.dart
Labels: size/XL

#881 feat: Add Debug Menu to Instant Config, Add Debug Menu item to User Menu
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/lib/instant_config/data/model/instant_config_data.dart
  metrics/web/lib/instant_config/domain/entities/instant_config.dart
  metrics/web/lib/instant_config/domain/usecases/fetch_instant_config_usecase.dart
  metrics/web/lib/instant_config/domain/usecases/parameters/instant_config_param.dart
  metrics/web/lib/instant_config/presentation/state/instant_config_notifier.dart
  metrics/web/lib/instant_config/presentation/view_models/debug_menu_instant_config_view_model.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/instant_config/data/model/instant_config_data_test.dart
  metrics/web/test/instant_config/domain/entities/instant_config_test.dart
  metrics/web/test/instant_config/domain/usecases/fetch_instant_config_usecase_test.dart
  metrics/web/test/instant_config/domain/usecases/parameters/instant_config_param_test.dart
  metrics/web/test/instant_config/presentation/state/instant_config_notifier_test.dart
  metrics/web/test/instant_config/presentation/view_models/debug_menu_instant_config_view_model_test.dart
  metrics/web/test/test_utils/instant_config_notifier_stub.dart
Labels: size/L

#890 feat: Create rules for Feature Config collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/feature-config-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: size/L

#891 fix: Migrate Feature Config onto new collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/instant-config-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
  metrics/web/lib/feature_config/data/repositories/firestore_feature_config_repository.dart
Labels: Snake 🐍, size/L

#894 fix: Change sync error message
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
Labels: Snake 🐍, size/XS

#895 fix: Fix links checker to include renamed files
  .github/workflows/metrics_actions.yml
Labels: Snake 🐍, size/XS

#893 docs: Debug Menu design document
  metrics/web/docs/features/debug_menu/01_debug_menu_design.md
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_data_layer_class_diagram.puml
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_domain_layer_class_diagram.puml
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_presentation_layer_class_diagram.puml
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_read_config_sequence_diagram.puml
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_update_config_sequence_diagram.puml
Labels: size/L

#899 fix: Update light and dark tooltip colors
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/web/icons/unknown_status.svg
Labels: size/S

#904 fix: Fix notifiers disposing
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/test_utils/matcher_util.dart
Labels: Snake 🐍, size/L

#898 docs: Navigator2.0: Design Document
  metrics/web/docs/features/navigation/01_navigation_design.md
  metrics/web/docs/features/navigation/diagrams/external_navigation_sequence_diagram.puml
  metrics/web/docs/features/navigation/diagrams/internal_navigation_sequence_diagram.puml
  metrics/web/docs/features/navigation/diagrams/navigation_class_diagram.puml
Labels: size/L

#901 feat: Implement Debug Menu Domain Layer
  metrics/web/lib/debug_menu/domain/entities/local_config.dart
  metrics/web/lib/debug_menu/domain/repositories/local_config_repository.dart
  metrics/web/lib/debug_menu/domain/usecases/close_local_config_storage_usecase.dart
  metrics/web/lib/debug_menu/domain/usecases/open_local_config_storage_usecase.dart
  metrics/web/lib/debug_menu/domain/usecases/parameters/local_config_param.dart
  metrics/web/lib/debug_menu/domain/usecases/read_local_config_usecase.dart
  metrics/web/lib/debug_menu/domain/usecases/update_local_config_usecase.dart
  metrics/web/test/debug_menu/domain/entities/local_config_test.dart
  metrics/web/test/debug_menu/domain/usecases/close_local_config_storage_usecase_test.dart
  metrics/web/test/debug_menu/domain/usecases/open_local_config_storage_usecase_test.dart
  metrics/web/test/debug_menu/domain/usecases/parameters/local_config_param_test.dart
  metrics/web/test/debug_menu/domain/usecases/read_local_config_usecase_test.dart
  metrics/web/test/debug_menu/domain/usecases/update_local_config_usecase_test.dart
  metrics/web/test/test_utils/local_config_repository_mock.dart
Labels: size/L

#908 feat: Add workflow to send a slack notification on build failed
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/metrics_integration_actions.yml
  .github/workflows/slack_notification_actions.yml
  .github/workflows/web_actions.yml
Labels: Snake 🐍, size/M

#909 feat: Implement Debug Menu Data Layer
  docs/16_dependencies_licenses.md
  metrics/web/lib/common/domain/entities/persistent_store_error_code.dart
  metrics/web/lib/common/presentation/models/persistent_store_error_message.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/debug_menu/data/model/local_config_data.dart
  metrics/web/lib/debug_menu/data/repositories/hive_local_config_repository.dart
  metrics/web/lib/debug_menu/domain/repositories/local_config_repository.dart
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/models/persistent_store_error_message_test.dart
  metrics/web/test/debug_menu/data/model/local_config_data_test.dart
Labels: size/L

#903 docs: create Sentry Design document
  metrics/web/docs/features/sentry/01_sentry_design.md
  metrics/web/docs/features/sentry/diagrams/sentry_util_class_diagram.puml
Labels: size/L

#922 fix: Fix sending slack notifications in Metrics Integration Actions
  .github/workflows/metrics_integration_actions.yml
Labels: Snake 🐍, size/XS

#920 feat: Update Github release actions to use Github CLI
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
Labels: size/L

#921 test: Migrate driver tests
  metrics/web/pubspec.yaml
  metrics/web/test_driver/integration_test.dart
Labels: size/L

#923 feat: Implement Debug Menu Presentation Layer
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/lib/debug_menu/presentation/state/debug_menu_notifier.dart
  metrics/web/lib/debug_menu/presentation/view_models/fps_monitor_local_config_view_model.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/debug_menu/presentation/state/debug_menu_notifier_test.dart
  metrics/web/test/debug_menu/presentation/view_models/fps_monitor_local_config_view_model_test.dart
  metrics/web/test/test_utils/debug_menu_notifier_mock.dart
  metrics/web/test/test_utils/debug_menu_notifier_stub.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/XL

#926 feat: Update driver run scripts to run integration tests
  metrics/web/test_driver/app.dart
  metrics/web/test_driver/app_test.dart
  metrics/web/test_driver/arguments/model/user_credentials.dart
  metrics/web/test_driver/cli/flutter/command/run_command_base.dart
  metrics/web/test_driver/cli/flutter/runner/flutter_drive_process_runner.dart
  metrics/web/test_driver/integration_test.dart
Labels: size/XL

#927 feat: Implement Debug Menu Theme
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/debug_menu/theme_data/debug_menu_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/debug_menu/debug_menu_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
Labels: size/L

#930 build: Update Flutter version
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/metrics_actions.yml
  .github/workflows/web_actions.yml
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
  docs/15_developer_configuration.md
  metrics/web/README.md
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/pubspec.yaml
Labels: size/L

#928 feat: Implement Debug Menu Page
  metrics/web/docs/features/debug_menu/01_debug_menu_design.md
  metrics/web/docs/features/debug_menu/diagrams/debug_menu_presentation_layer_class_diagram.puml
  metrics/web/lib/analytics/domain/entities/page_name.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/lib/common/presentation/routes/route_name.dart
  metrics/web/lib/common/presentation/widgets/metrics_fps_monitor.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/lib/debug_menu/presentation/pages/debug_menu_page.dart
  metrics/web/lib/debug_menu/presentation/state/debug_menu_notifier.dart
  metrics/web/lib/debug_menu/presentation/view_models/local_config_fps_monitor_view_model.dart
  metrics/web/lib/debug_menu/presentation/view_models/renderer_display_view_model.dart
  metrics/web/lib/debug_menu/presentation/widgets/debug_menu_fps_monitor_toggle.dart
  metrics/web/lib/debug_menu/presentation/widgets/debug_menu_renderer_display.dart
  metrics/web/lib/debug_menu/strings/debug_menu_strings.dart
  metrics/web/lib/main.dart
  metrics/web/test/analytics/domain/entities/page_name_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
  metrics/web/test/common/presentation/widgets/metrics_fps_monitor_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/debug_menu/presentation/pages/debug_menu_page_test.dart
  metrics/web/test/debug_menu/presentation/state/debug_menu_notifier_test.dart
  metrics/web/test/debug_menu/presentation/view_models/local_config_fps_monitor_view_model_test.dart
  metrics/web/test/debug_menu/presentation/view_models/renderer_display_view_model_test.dart
  metrics/web/test/debug_menu/presentation/widgets/debug_menu_fps_monitor_toggle_test.dart
  metrics/web/test/debug_menu/presentation/widgets/debug_menu_renderer_display_test.dart
  metrics/web/test/test_utils/debug_menu_notifier_stub.dart
Labels: size/XXL

#925 docs: CI Integrations user guide
  metrics/ci_integrations/docs/02_ci_integration_user_guide.md
  metrics/ci_integrations/docs/buildkite/config/configuration_template.yaml
  metrics/ci_integrations/docs/destination/firestore/config/configuration_template.yaml
  metrics/ci_integrations/docs/github_actions/config/configuration_template.yaml
  metrics/ci_integrations/docs/source/buildkite/01_buildkite_client.md
  metrics/ci_integrations/docs/source/buildkite/config/configuration_template.yaml
  metrics/ci_integrations/docs/source/buildkite/diagrams/buildkite_client_class_diagram.puml
  metrics/ci_integrations/docs/source/github_actions/01_github_actions_client.md
  metrics/ci_integrations/docs/source/github_actions/config/configuration_template.yaml
  metrics/ci_integrations/docs/source/github_actions/diagrams/github_actions_client_class_diagram.puml
  metrics/ci_integrations/docs/source/jenkins/config/configuration_template.yaml
Labels: size/L

#931 feat: Implement RouteConfiguration
  metrics/web/lib/analytics/domain/entities/page_name.dart
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/drawer/widget/metrics_drawer.dart
  metrics/web/lib/common/presentation/navigation/constants/metrics_routes.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_name.dart
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/lib/common/presentation/routes/route_name.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/test/analytics/domain/entities/page_name_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_name_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/common/presentation/routes/metrics_page_route_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
Labels: size/L

#932 docs: GitHub Actions CI Integrations setup guide
  docs/18_github_actions_metrics_integration.md
  docs/diagrams/github_actions_sequence_diagram.puml
Labels: size/L

#942 fix: Fix resetting project group dialog view models
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: Snake 🐍, size/L

#929 test: More tests for project groups
  metrics/web/pubspec.yaml
  metrics/web/test_driver/app_test.dart
  metrics/web/test_driver/flutter_web_driver.dart
  metrics/web/test_driver/test_utils/hover_widget.dart
  metrics/web/test_driver/test_utils/pump_and_settle_widget.dart
Labels: size/L

#945 docs: Add uuid dependency to the dependencies document
  docs/16_dependencies_licenses.md
Labels: Snake 🐍, size/XS

#941 feat: Implement MetricsPage and MetricsPageFactory
  metrics/web/docs/features/navigation/diagrams/navigation_class_diagram.puml
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page.dart
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_factory.dart
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_route.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_route_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
  metrics/web/test/test_utils/matcher_util.dart
Labels: size/L

#946 build: Add Sentry autoreleases
  .github/workflows/web_actions.yml
Labels: size/M

#947 test: Improve project group dialog tests
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: Snake 🐍, size/L

#943 docs: Update designs with MetricsLogger
  metrics/web/docs/features/metrics_logger/01_metrics_logger_design.md
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_class_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_initialize_sequence_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_log_error_sequence_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_sentry_class_diagram.puml
  metrics/web/docs/features/sentry/01_sentry_design.md
  metrics/web/docs/features/sentry/diagrams/sentry_util_class_diagram.puml
Labels: size/XL

#951 feat: implement Metrics Logger
  metrics/web/lib/metrics_logger/metrics_logger.dart
  metrics/web/lib/metrics_logger/writer/logger_writer.dart
  metrics/web/test/metrics_logger/metrics_logger_test.dart
Labels: size/L

#950 docs: Update Navigator2.0 design
  metrics/web/docs/features/navigation/01_navigation_design.md
  metrics/web/docs/features/navigation/diagrams/internal_navigation_sequence_diagram.puml
  metrics/web/docs/features/navigation/diagrams/navigation_class_diagram.puml
  metrics/web/docs/features/navigation/diagrams/not_initialized_app_navigation_sequence_diagram.puml
Labels: Snake 🐍, size/M

#948 feat: Implement Navigation Notifier
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/constants/metrics_routes.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
Labels: size/XL
