Repository Flank/flank-dashboard, pull requests merged in 2020-09, with the labels that each got.

#487 feat: Implement metrics user menu card
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/user_menu_theme_data.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/toggle/widgets/toggle.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu_card.dart
  metrics/web/test/common/presentation/metrics_theme/model/user_menu_theme_data_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_card_test.dart
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: size/L

#492 test: Add test for single-line text in project group dropdown button
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
Labels: size/S

#483 feat: Project groups page toasts
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/project_group_dialog_strategy.dart
  metrics/web/pubspec.yaml
  metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
  metrics/web/test/project_groups/presentation/strings/project_groups_strings_test.dart
  metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy_test.dart
Labels: size/L

#494 feat: Login page toasts
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
Labels: size/M

#497 fix: Update chromedriver version
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: size/XS

#503 fix: Remove driver tests from the metrics GitHub action
  .github/workflows/web_app_actions.yml
Labels: size/XS

#504 fix: Enable driver tests and add post frame callback to the loading page
  .github/workflows/web_app_actions.yml
  metrics/web/lib/auth/presentation/pages/loading_page.dart
Labels: size/XS

#495 feat: Show a MetricsToast on each user action/error on the dashboard page
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
Labels: size/M

#481 fix: Improve Project Groups Layout, Implement TappableArea, Implement MetricsCard
  metrics/web/lib/base/presentation/constants/mouse_cursor.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_inactive_button.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_card.dart
  metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
  metrics/web/pubspec.lock
  metrics/web/test/base/presentation/widgets/tappable_area_test.dart
  metrics/web/test/common/presentation/button/widgets/metrics_inactive_button_test.dart
  metrics/web/test/common/presentation/widgets/metrics_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart
  metrics/web/web/icons/add.svg
  metrics/web/web/icons/arrow-back.svg
  metrics/web/web/icons/delete.svg
  metrics/web/web/icons/edit.svg
Labels: size/XXL

#509 fix: Rendering issue of project groups project list
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
Labels: size/M

#506 fix: Dashboard: Project name filter persists on navigation
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/S

#500 feat: Implement the metrics user menu
  metrics/web/lib/base/presentation/widgets/base_popup.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/routes/observers/overlay_entry_route_observer.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu_button.dart
  metrics/web/lib/main.dart
  metrics/web/test/base/presentation/widgets/base_popup_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_button_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/web/icons/avatar_active.svg
Labels: size/XL

#512 fix: Update Metrics Logo icon
  metrics/web/web/icons/logo-metrics.svg
Labels: size/S

#517 fix: Fix Add Project Group Card test coverage
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/attention_level/add_project_group_card_attention_level_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/style/add_project_group_card_style_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/theme_data/add_project_group_card_theme_data_test.dart
Labels: size/M

#519 fix: Minor documentation and code improvements
  metrics/web/lib/base/presentation/decoration/bubble_shape_border.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/toast/widgets/negative_toast.dart
  metrics/web/lib/common/presentation/toast/widgets/positive_toast.dart
  metrics/web/lib/common/presentation/toast/widgets/toast.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/base/presentation/widgets/tappable_area_test.dart
Labels: Snake 🐍, size/M

#515 feat: Handle authentication errors
  metrics/web/lib/auth/data/converter/firebase_auth_error_code_converter.dart
  metrics/web/lib/auth/data/model/firebase_auth_error_code.dart
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/auth/domain/entities/auth_error_code.dart
  metrics/web/lib/auth/presentation/models/auth_error_message.dart
  metrics/web/lib/auth/presentation/strings/auth_strings.dart
  metrics/web/test/auth/data/converter/firebase_auth_error_code_converter_test.dart
Labels: size/L

#527 fix: Update Metrics Logo icon in App Bar
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/web/icons/logo-metrics-appbar.svg
Labels: Snake 🐍, size/S

#521 feat: Create the Metrics theme mode image widget
  metrics/web/lib/common/presentation/widgets/metrics_theme_image.dart
  metrics/web/test/common/presentation/drawer/widget/metrics_drawer_test.dart
  metrics/web/test/common/presentation/widgets/metrics_theme_image_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/test_utils/theme_notifier_mock.dart
Labels: size/L

#514 feat: Email domain validation function
  metrics/firebase/functions/index.js
Labels: size/M

#535 fix: Improve dropdown item hover effect
  metrics/web/lib/base/presentation/widgets/dropdown_item.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/dropdown/theme/theme_data/dropdown_item_theme_data.dart
  metrics/web/lib/common/presentation/dropdown/widgets/metrics_dropdown_item.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/test/base/presentation/widgets/dropdown_item_test.dart
  metrics/web/test/base/presentation/widgets/tappable_area_test.dart
  metrics/web/test/common/presentation/dropdown/theme/theme_data/dropdown_item_theme_data_test.dart
Labels: Tiger 🐯, size/L

#537 fix: Dropdown Item test descritions and readability fixes
  metrics/web/lib/base/presentation/widgets/dropdown_item.dart
  metrics/web/test/base/presentation/widgets/dropdown_item_test.dart
Labels: Snake 🐍, size/XS

#536 feat: Metrics text style
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/widgets/metrics_card.dart
  metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_style.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_style_test.dart
Labels: size/L

#543 fix: Disable drawer edge swipe
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
Labels: size/S

#530 refactor: Improve naming Metric -> Metrics
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_widget_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/metrics_theme.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/strategy/value_based_appearance_strategy.dart
  metrics/web/lib/dashboard/presentation/view_models/project_metrics_tile_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_number_scorecard.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/metrics_value_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/styled_circle_percentage.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metric_widget_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/widget/metrics_theme_test.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/coverage_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/no_data_placeholder_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/stability_circle_percentage_test.dart
  metrics/web/test_driver/app_test.dart
Labels: size/L

#548 feat: Introduce the Light Theme for common widgets
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/dropdown/widgets/metrics_dropdown_item.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_field_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/main.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/web/icons/logo-metrics-appbar-light.svg
Labels: size/L

#549 feat: Introduce the Light Theme for the Login Page
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/auth/presentation/widgets/sign_in_option_button.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/web/icons/logo-google.svg
  metrics/web/web/icons/logo-metrics-light.svg
Labels: size/M

#550 fix: Remove the user item.
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart
Labels: size/M

#545 feat: Add active search icon
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/web/icons/search-focused.svg
Labels: size/M

#557 fix: Upgrade node-forge version to version 0.10.0 or later
  metrics/firebase/functions/package-lock.json
  metrics/firebase/functions/package.json
  metrics/firebase/package-lock.json
  metrics/firebase/package.json
Labels: size/XS

#556 feat: Dashboard project search - add focused search icon
  metrics/web/lib/dashboard/presentation/widgets/projects_search_input.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
Labels: size/XS

#558 fix: Remove font-weight on the checked checkbox
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
Labels: size/XS

#544 feat: Add password toggle visibility icon.
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/web/icons/eye_off.svg
  metrics/web/web/icons/eye_on.svg
Labels: size/L

#561 feat: Introduce the Light Theme to the Dashboard page
  metrics/web/lib/base/presentation/widgets/dropdown_body.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dropdown_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/test/base/presentation/widgets/dropdown_body_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dropdown_theme_data_test.dart
Labels: size/L

#563 fix: Remove checkbox selection animation
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/main.dart
Labels: size/XS

#574 fix: If user didn't change data on modal dialog - save button should be inactive
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: size/L

#576 fix: Add empty space after all project group cards
  metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
Labels: size/S

#568 fix: Disable buttons highlights.
  metrics/web/lib/base/presentation/widgets/icon_label_button.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_button.dart
  metrics/web/lib/common/presentation/user_menu_button/widgets/metrics_user_menu_button.dart
  metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
  metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
  metrics/web/lib/main.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
  metrics/web/test/base/presentation/widgets/tappable_area_test.dart
  metrics/web/test/common/presentation/user_menu_button/widgets/metrics_user_menu_button_test.dart
  metrics/web/test/common/presentation/widgets/metrics_page_title_test.dart
Labels: size/L

#569 fix: Add backdrop color for dialogs
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dialog_theme_data_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
Labels: size/L

#541 feat: Email domain validation
  metrics/web/lib/auth/data/model/email_domain_validation_request_data.dart
  metrics/web/lib/auth/data/model/email_domain_validation_result_data.dart
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/auth/domain/entities/auth_credentials.dart
  metrics/web/lib/auth/domain/entities/auth_error_code.dart
  metrics/web/lib/auth/domain/entities/email_domain_validation_result.dart
  metrics/web/lib/auth/domain/repositories/user_repository.dart
  metrics/web/lib/auth/domain/usecases/google_sign_in_usecase.dart
  metrics/web/pubspec.yaml
  metrics/web/test/auth/data/model/email_domain_validation_request_data_test.dart
  metrics/web/test/auth/data/model/email_domain_validation_result_data_test.dart
  metrics/web/test/auth/domain/entities/auth_credentials_test.dart
  metrics/web/test/auth/domain/entities/email_domain_validation_result_test.dart
  metrics/web/test/auth/domain/usercases/google_sign_in_usecase_test.dart
Labels: size/L

#562 fix: Remove animations on page transitions
  metrics/web/lib/common/presentation/routes/metrics_page_route.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/test/common/presentation/routes/metrics_page_route_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
Labels: size/L

#581 fix: Remove modal dialog shadow
  metrics/web/lib/main.dart
Labels: size/XS

#570 fix: Icon buttons on hover state should be a bit darker
  metrics/web/lib/base/presentation/widgets/icon_label_button.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_card_theme_data.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
  metrics/web/test/base/presentation/widgets/tappable_area_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_card_theme_data_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
Labels: size/L

#586 fix: Email domain validation error message and google sign-in pop-up
  metrics/firebase/functions/package.json
  metrics/web/lib/auth/presentation/models/auth_error_message.dart
  metrics/web/lib/auth/presentation/strings/auth_strings.dart
  metrics/web/test/auth/presentation/models/auth_error_message_test.dart
  metrics/web/web/index.html
Labels: size/M

#582 fix: On user logout clear saved project groups on the Dashboard
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
Labels: size/M

#595 fix: Improve checkbox to apply the hover effect like on the designs.
  metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
  metrics/web/web/icons/check-box-blank-hovered.svg
  metrics/web/web/icons/check-box-hovered.svg
Labels: size/L

#580 fix: Remove button shadows
  metrics/web/lib/common/presentation/button/theme/style/metrics_button_style.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/test/common/presentation/button/theme/style/metrics_button_style_test.dart
Labels: size/S

#585 fix: Remove an additional scroll stretching effect
  metrics/web/lib/common/presentation/widgets/metrics_scroll_behavior.dart
  metrics/web/lib/main.dart
Labels: size/S

#598 fix: Implement hover state for Metrics Project Tile
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
Labels: size/L

#588 fix: Improve mouse cursors on Metrics elements
  metrics/web/lib/base/presentation/widgets/info_dialog.dart
  metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
  metrics/web/test/base/presentation/widgets/info_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
Labels: size/M

#579 feat: Introduce the light theme to the Project groups page
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/text_field_theme_data.dart
  metrics/web/lib/common/presentation/page_title/theme/page_title_theme_data.dart
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/dashboard/presentation/widgets/projects_search_input.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/text_field_theme_data_test.dart
  metrics/web/test/common/presentation/page_title/theme/page_title_theme_data_test.dart
  metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/web/icons/avatar_active.svg
  metrics/web/web/icons/disabled-add.svg
  metrics/web/web/icons/search-focused.svg
Labels: size/XL

#606 fix: Fix checkbox tile pointer
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
Labels: size/M

#583 fix: Improve Light theme for the Dashboard Page
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/user_menu_button/theme/user_menu_button_theme_data.dart
  metrics/web/lib/common/presentation/user_menu_button/widgets/metrics_user_menu_button.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/user_menu_button/theme/user_menu_button_theme_test.dart
  metrics/web/test/common/presentation/user_menu_button/widgets/metrics_user_menu_button_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: size/L

#613 fix: Fix password visibility icon color in Light Theme
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/login_theme_data_test.dart
Labels: size/M

#612 feat: Add inactive state for the sign-in option button
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/sign_in_option_button.dart
  metrics/web/lib/auth/presentation/widgets/strategy/google_sign_in_option_appearance_strategy.dart
  metrics/web/lib/auth/presentation/widgets/strategy/sign_in_option_appearance_strategy.dart
  metrics/web/lib/auth/presentation/widgets/strategy/sign_in_option_strategy.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/auth/presentation/widgets/sign_in_option_button_test.dart
  metrics/web/test/auth/presentation/widgets/strategy/google_sign_in_option_appearance_strategy_test.dart
  metrics/web/test/auth/presentation/widgets/strategy/sign_in_option_appearance_strategy_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/login_theme_data_test.dart
Labels: size/L

#614 feat: Login Page theme matches OS theme
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/metrics_theme/state/theme_notifier.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/common/presentation/metrics_theme/state/theme_notifier_test.dart
Labels: size/L

#616 feat: Implement Bar Graph Popup theme
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/bar_graph_popup/theme_data/bar_graph_popup_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/test/common/presentation/metrics_theme/model/bar_graph_popup/theme_data/bar_graph_popup_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
Labels: size/L

#607 feat: Fps monitor
  metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
  metrics/web/lib/base/presentation/widgets/keyboard_shortcuts.dart
  metrics/web/lib/common/presentation/widgets/metrics_fps_monitor.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/main.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/graphs/circle_percentage_test.dart
  metrics/web/test/base/presentation/widgets/keyboard_shortcuts_test.dart
  metrics/web/test/common/presentation/widgets/metrics_fps_monitor_test.dart
Labels: size/XL

#628 fix: Add empty space after last element on the dashboard
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
Labels: size/XS

#627 build: Update Flutter version to the latest beta
  .github/workflows/web_app_actions.yml
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
  metrics/web/README.md
  metrics/web/lib/auth/presentation/pages/loading_page.dart
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/lib/base/presentation/widgets/value_form_field.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/base/presentation/widgets/value_form_field_test.dart
Labels: size/M

#619 build: Deploy HTML and SKIA versions at once
  .github/workflows/web_app_actions.yml
  metrics/web/.firebaserc
  metrics/web/firebase.json
Labels: size/M

#626 fix: Improve Project Groups Dropdown animation
  metrics/web/lib/base/presentation/widgets/dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/test/base/presentation/widgets/dropdown_body_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart
Labels: size/L

#635 fix: Fix theme toggle switches its value on hover
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/toggle/widgets/toggle_test.dart
Labels: size/M

#632 feat: Add security rules for a user profile
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
  metrics/firebase/test/firestore/rules/user-profiles-test.js
Labels: size/L
