Repository Flank/flank-dashboard, pull requests merged in 2020-08, with the labels that each got.

#376 Performance sparkline improvements
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/view_models/performance_sparkline_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/strings/common_strings_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/performance_sparkline_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
Labels: size/M

#379 Change the Login page appearance
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/auth/presentation/strings/auth_strings.dart
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/sign_in_option_button.dart
  metrics/web/lib/auth/presentation/widgets/strategy/google_sign_in_option_strategy.dart
  metrics/web/lib/auth/presentation/widgets/strategy/sign_in_option_strategy.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/main.dart
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/auth/presentation/widgets/sign_in_option_button_test.dart
  metrics/web/test/auth/presentation/widgets/strategy/google_sign_in_option_strategy_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/test_utils/finder_util.dart
  metrics/web/test/test_utils/metrics_themed_testbed.dart
  metrics/web/test_driver/app_test.dart
Labels: size/XL

#383 Metrics table theme
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/metrics_table_header_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/metrics_table_header_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
Labels: size/L

#406 Create scorecard theme
  metrics/web/lib/base/presentation/widgets/scorecard.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/scorecard/theme_data/scorecard_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/build_number_scorecard.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/scorecard/theme_data/scorecard_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_number_scorecard_test.dart
Labels: size/L

#409 Implement the base popup widget
  metrics/web/lib/base/presentation/widgets/base_popup.dart
  metrics/web/test/base/presentation/widgets/base_popup_test.dart
Labels: size/L

#404 Add sparkline theme and apply to the sparkline widget.
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/sparkline/theme_data/sparkline_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/sparkline/theme_data/sparkline_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
Labels: size/L

#401 Create project build status theme
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_build_status/attention_level/project_build_status_attention_level.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_build_status/style/project_build_status_style.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_build_status/theme_data/project_build_status_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/strategy/value_based_theme_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/coverage_circle_percentage.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/stability_circle_percentage.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/metrics_value_theme_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/themed_circle_percentage.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_build_status/attention_level/project_build_status_attention_level_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_build_status/style/project_build_status_style_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_build_status/theme_data/project_build_status_theme_data_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/coverage_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
  metrics/web/test/dashboard/presentation/widgets/stability_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/metrics_value_theme_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/themed_circle_percentage_test.dart
Labels: size/XL

#424 Renamed MyApp to MetricsApp
  metrics/web/lib/app.dart
  metrics/web/lib/main.dart
Labels: size/S

#425 Create decorated container
  metrics/web/lib/base/presentation/graphs/colored_bar.dart
  metrics/web/lib/base/presentation/widgets/decorated_container.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/base/presentation/graphs/colored_bar_test.dart
  metrics/web/test/base/presentation/widgets/decorated_container_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
  metrics/web/test/test_utils/finder_util.dart
Labels: size/L

#413 Create Metrics user menu theme and Metrics toggle theme.
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/toggle_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/user_menu_theme_data.dart
  metrics/web/pubspec.lock
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/toggle_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/user_menu_theme_data_test.dart
Labels: size/L

#417 Update firebase rules
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/package-lock.json
  metrics/firebase/package.json
  metrics/firebase/test/firestore/rules/project-groups-test.js
Labels: size/L

#423 Implement characters limit for the project group name.
  metrics/web/lib/project_groups/domain/value_objects/exceptions/project_group_name_validation_error_code.dart
  metrics/web/lib/project_groups/domain/value_objects/project_group_name.dart
  metrics/web/lib/project_groups/presentation/models/project_group_name_validation_error_message.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/test/project_groups/domain/value_objects/project_group_name_test.dart
  metrics/web/test/project_groups/presentation/models/project_group_name_validation_error_message_test.dart
Labels: size/M

#426 Handled no search results state on Dashboard. Added test for no search results case.
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
  metrics/web/test_driver/app_test.dart
Labels: size/M

#431 Sparkline graph single build
  metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
  metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
Labels: size/M

#435 Added null checks for Scorecard. Fixed tests for null cases in Scorecard tests
  metrics/web/lib/base/presentation/widgets/scorecard.dart
  metrics/web/test/base/presentation/widgets/scorecard_test.dart
Labels: size/S

#437 Improved async tests in ProjectMetricsNotifier
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
Labels: size/M

#439 Handle `no search results` state
  metrics/web/lib/base/presentation/widgets/text_placeholder.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/text_placeholder/theme/theme_data/text_placeholder_theme_data.dart
  metrics/web/lib/common/presentation/text_placeholder/widgets/text_placeholder.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_placeholder.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
  metrics/web/test/base/presentation/widgets/text_placeholder_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/text_placeholder/theme/theme_data/text_placeholder_theme_data_test.dart
  metrics/web/test/common/presentation/text_placeholder/widgets/text_placeholder_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_view_test.dart
  metrics/web/test/test_utils/project_groups_notifier_stub.dart
Labels: size/L

#440 set firebase project using CLI
  docs/14_firebase_deployment_cli.md
Labels: size/L

#433 Add tests for the project group dialog
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: size/XL

#453 Ensure the dashboard page matches the designs perfectly
  metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/projects_search_input.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
  metrics/web/web/icons/avatar.svg
  metrics/web/web/icons/dropdown.svg
  metrics/web/web/icons/logo-metrics.svg
Labels: size/L

#441 Implement NoSearchResultsPlaceholder
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/no_search_results_placeholder.dart
  metrics/web/pubspec.lock
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/no_search_results_placeholder_test.dart
  metrics/web/test_driver/app_test.dart
Labels: size/L

#458 Metrics table tile loading placeholder
  metrics/web/lib/base/presentation/widgets/shimmer_container.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/shimmer_placeholder/theme_data/shimmer_placeholder_theme_data.dart
  metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_loading_placeholder.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/widgets/shimmer_container_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/shimmer_placeholder/theme_data/shimmer_placeholder_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_loading_placeholder_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/XL

#468 feat: add Mergify bot to speed up merging of PRs
  .github/workflows/web_app_actions.yml
  .mergify.yaml
  docs/02_process.md
  metrics/web/pubspec.lock
Labels: size/M

#474 Mergify: configuration update
  .mergify.yml
Labels: size/S

#471 chore: Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/web_app_actions.yml
Labels: size/M

#475 fix: Delete old Mergify
  .mergify.yaml
Labels: size/S

#476 fix: automatic builds
  .github/workflows/web_app_actions.yml
Labels: size/XS

#466 feat: Metrics table header loading placeholder
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header_loading_placeholder.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_loading_header.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_title_header.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_loading_placeholder_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_loading_header_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_title_header_test.dart
Labels: size/XL

#461 feat: Add Google Sign-In
  docs/09_firebase_deployment.md
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/auth/domain/repositories/user_repository.dart
  metrics/web/lib/auth/domain/usecases/google_sign_in_usecase.dart
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/strategy/google_sign_in_option_strategy.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/pubspec.yaml
  metrics/web/test/auth/domain/usercases/google_sign_in_usecase_test.dart
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/auth/presentation/state/auth_notifier_test.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/auth/presentation/widgets/strategy/google_sign_in_option_strategy_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
  metrics/web/web/index.html
Labels: size/XL

#477 feat: Add input loading placeholders
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/widgets/metrics_input_placeholder.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_search_input.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/widgets/metrics_input_placeholder_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_search_input_test.dart
Labels: size/L

#478 style: Circle percentage theme data
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/circle_percentage/attention_level/circle_percentage_attention_level.dart
  metrics/web/lib/common/presentation/metrics_theme/model/circle_percentage/style/circle_percentage_style.dart
  metrics/web/lib/common/presentation/metrics_theme/model/circle_percentage/theme_data/circle_percentage_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_circle_percentage_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/metrics_theme.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/strategy/value_based_appearance_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/coverage_circle_percentage.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/stability_circle_percentage.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/metrics_value_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/styled_circle_percentage.dart
  metrics/web/lib/dashboard/presentation/widgets/themed_circle_percentage.dart
  metrics/web/test/common/presentation/metrics_theme/model/circle_percentage/attention_level/circle_percentage_attention_level_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/circle_percentage/style/circle_percentage_style_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/circle_percentage/theme_data/circle_percentage_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metric_circle_percentage_theme_data.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/coverage_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
  metrics/web/test/dashboard/presentation/widgets/stability_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/metrics_value_style_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/metrics_value_theme_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/styled_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/themed_circle_percentage_test.dart
Labels: size/XXL

#457 feat: Implement project ids limitation.
  metrics/web/lib/base/presentation/widgets/value_form_field.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/project_groups/domain/value_objects/exceptions/project_group_projects_validation_error_code.dart
  metrics/web/lib/project_groups/domain/value_objects/exceptions/project_group_projects_validation_exception.dart
  metrics/web/lib/project_groups/domain/value_objects/project_group_projects.dart
  metrics/web/lib/project_groups/presentation/models/project_group_projects_validation_error_message.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/lib/project_groups/presentation/validators/project_group_projects_validator.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/base/presentation/widgets/value_form_field_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
  metrics/web/test/project_groups/domain/value_objects/exceptions/project_group_projects_validation_exception_test.dart
  metrics/web/test/project_groups/domain/value_objects/project_group_projects_test.dart
  metrics/web/test/project_groups/presentation/models/project_group_projects_validation_error_message_test.dart
  metrics/web/test/project_groups/presentation/strings/project_groups_strings_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: size/XL

#473 feat: Create Disabled Add Project Group Card
  metrics/web/lib/common/presentation/metrics_theme/model/add_project_group_card/attention_level/add_project_group_card_attention_level.dart
  metrics/web/lib/common/presentation/metrics_theme/model/add_project_group_card/style/add_project_group_card_style.dart
  metrics/web/lib/common/presentation/metrics_theme/model/add_project_group_card/theme_data/add_project_group_card_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/attention_level/add_project_group_card_attention_level_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/style/add_project_group_card_style_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/theme_data/add_project_group_card_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_view_test.dart
  metrics/web/test/test_utils/project_groups_notifier_stub.dart
  metrics/web/web/icons/add.svg
  metrics/web/web/icons/disabled-add.svg
Labels: size/XL

#480 feat: Create toast widget
  metrics/web/lib/common/presentation/constants/duration_constants.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/routes/observers/toast_route_observer.dart
  metrics/web/lib/common/presentation/toast/theme/attention_level/toast_attention_level.dart
  metrics/web/lib/common/presentation/toast/theme/style/toast_style.dart
  metrics/web/lib/common/presentation/toast/theme/theme_data/toast_theme_data.dart
  metrics/web/lib/common/presentation/toast/widgets/negative_toast.dart
  metrics/web/lib/common/presentation/toast/widgets/positive_toast.dart
  metrics/web/lib/common/presentation/toast/widgets/toast.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/main.dart
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/toast/theme/attention_level/toast_attention_level_test.dart
  metrics/web/test/common/presentation/toast/theme/style/toast_style_test.dart
  metrics/web/test/common/presentation/toast/theme/theme_data/toast_theme_data_test.dart
  metrics/web/test/common/presentation/toast/widget/negative_toast_test.dart
  metrics/web/test/common/presentation/toast/widget/positive_toast_test.dart
  metrics/web/test/common/presentation/toast/widget/toast_test.dart
Labels: size/XL

#443 feat: Implement the bubble shape border.
  metrics/web/lib/base/presentation/decoration/bubble_shape_border.dart
  metrics/web/test/base/presentation/decoration/bubble_shape_border_test.dart
Labels: size/L

#482 ci: add conventional commits PR checks workflow and documentation
  .github/workflows/pr_checks.yml
  docs/02_process.md
Labels: size/M

#489 fix: add single line text to the dropdown menu button
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
Labels: size/XS
