Repository Flank/flank-dashboard, pull requests merged in 2020-10, with the labels that each got.

#636 feat: User profile domain layer
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/auth/domain/entities/theme_type.dart
  metrics/web/lib/auth/domain/entities/user_profile.dart
  metrics/web/lib/auth/domain/repositories/user_repository.dart
  metrics/web/lib/auth/domain/usecases/create_user_profile_usecase.dart
  metrics/web/lib/auth/domain/usecases/parameters/user_id_param.dart
  metrics/web/lib/auth/domain/usecases/parameters/user_profile_param.dart
  metrics/web/lib/auth/domain/usecases/receive_user_profile_updates.dart
  metrics/web/lib/auth/domain/usecases/update_user_profile_usecase.dart
  metrics/web/test/auth/domain/entities/user_profile_test.dart
  metrics/web/test/auth/domain/usercases/create_user_profile_usecase_test.dart
  metrics/web/test/auth/domain/usercases/params/user_id_param_test.dart
  metrics/web/test/auth/domain/usercases/params/user_profile_param_test.dart
  metrics/web/test/auth/domain/usercases/receive_user_profile_updates_test.dart
  metrics/web/test/auth/domain/usercases/update_user_profile_usecase_test.dart
Labels: size/L

#643 fix: Long project group name padding
  metrics/web/lib/base/presentation/widgets/info_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/base/presentation/widgets/info_dialog_test.dart
Labels: size/L

#640 feat: User profile data
  metrics/web/lib/auth/data/model/user_profile_data.dart
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/test/auth/data/model/user_profile_data_test.dart
Labels: size/L

#651 feat: Create Github Actions client documentation
  metrics/ci_integrations/docs/github_actions/01_github_actions_client.md
  metrics/ci_integrations/docs/github_actions/diagrams/github_actions_client_class_diagram.puml
Labels: size/L

#638 fix: Display error messages near input fields
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/main.dart
  metrics/web/test/auth/presentation/state/auth_notifier_test.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/L

#631 fix: Long dropdown list have height of 5.5 items
  metrics/web/lib/base/presentation/widgets/dropdown_menu.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/test/base/presentation/widgets/dropdown_menu_test.dart
Labels: size/M

#653 feat: Deploy firebase security rules using Github Actions
  .github/workflows/firebase_actions.yml
Labels: size/M

#647 feat: User profile theme design
  metrics/web/docs/features/user_profile_theme/01_user_profile_theme_design.md
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_creation_sequence.puml
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_theme_data_class.puml
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_theme_domain_class.puml
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_theme_presentation_class.puml
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_theme_presentation_sequence.puml
Labels: size/L

#664 fix: Fix Project Group Dialog NoSuchMethodException on close
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
Labels: size/M

#661 ci: Implement GitHub Actions RunStatus, RunConclusion mappers
  metrics/ci_integrations/lib/client/github_actions/mappers/run_conclusion_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/mappers/run_status_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/models/run_conclusion.dart
  metrics/ci_integrations/lib/client/github_actions/models/run_status.dart
  metrics/ci_integrations/lib/client/jenkins/mapper/jenkins_build_result_mapper.dart
  metrics/ci_integrations/lib/integration/interface/base/client/mapper/mapper.dart
  metrics/ci_integrations/test/client/github_actions/mappers/run_conclusion_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/mappers/run_status_mapper_test.dart
Labels: size/L

#669 fix: Fix diagram links in user profile theme design document
  metrics/web/docs/features/user_profile_theme/01_user_profile_theme_design.md
Labels: size/S

#665 fix: Circle percentage widget with null value
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/test/base/presentation/graphs/circle_percentage_test.dart
Labels: size/M

#634 feat: Implement Dashboard Bar graph popup
  metrics/web/lib/base/presentation/graphs/bar_graph.dart
  metrics/web/lib/base/presentation/graphs/colored_bar.dart
  metrics/web/lib/base/presentation/widgets/base_popup.dart
  metrics/web/lib/base/presentation/widgets/circle_graph_indicator.dart
  metrics/web/lib/common/presentation/colored_bar/strategy/metrics_colored_bar_appearance_strategy.dart
  metrics/web/lib/common/presentation/colored_bar/theme/attention_level/metrics_colored_bar_attention_level.dart
  metrics/web/lib/common/presentation/colored_bar/theme/style/metrics_colored_bar_style.dart
  metrics/web/lib/common/presentation/colored_bar/theme/theme_data/metrics_colored_bar_theme_data.dart
  metrics/web/lib/common/presentation/colored_bar/widgets/metrics_colored_bar.dart
  metrics/web/lib/common/presentation/graph_indicator/theme/attention_level/graph_indicator_attention_level.dart
  metrics/web/lib/common/presentation/graph_indicator/theme/style/graph_indicator_style.dart
  metrics/web/lib/common/presentation/graph_indicator/theme/theme_data/graph_indicator_theme_data.dart
  metrics/web/lib/common/presentation/graph_indicator/widgets/graph_indicator.dart
  metrics/web/lib/common/presentation/graph_indicator/widgets/negative_graph_indicator.dart
  metrics/web/lib/common/presentation/graph_indicator/widgets/neutral_graph_indicator.dart
  metrics/web/lib/common/presentation/graph_indicator/widgets/positive_graph_indicator.dart
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/build_results_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/metrics_theme.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_popup_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_popup_card.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy.dart
  metrics/web/lib/main.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/graphs/bar_graph_test.dart
  metrics/web/test/base/presentation/graphs/colored_bar_test.dart
  metrics/web/test/base/presentation/widgets/base_popup_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/build_results_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
Labels: size/XXL

#663 feat: Performance chart group data by day.
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
Labels: size/M

#672 fix: Disable "Space" hotkey for the fps monitor.
  metrics/web/lib/base/presentation/widgets/keyboard_shortcuts.dart
Labels: size/S

#666 ci: Implement WorkflowRun, WorkflowRunDuration, WorkflowRunArtifact models
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_artifact.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_duration.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_artifact_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_duration_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
Labels: size/L

#679 docs: Improve documentation to include supported browsers and run instructions
  docs/09_firebase_deployment.md
  docs/15_developer_configuration.md
  readme.md
Labels: size/L

#683 fix: Make Sparkline more smooth
  metrics/web/lib/base/presentation/graphs/sparkline_graph.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/test/base/presentation/graphs/sparkline_graph_test.dart
Labels: size/L

#685 fix: Move metrics text style to an appropriate package
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_text/style/metrics_text_style.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_text/style/metrics_text_style_test.dart
Labels: size/S

#673 docs: Enable public_member_api_docs linter rule and fix documentation.
  analysis_options.yaml
  metrics/web/lib/auth/data/model/firebase_auth_error_code.dart
  metrics/web/lib/auth/domain/entities/authentication_exception.dart
  metrics/web/lib/auth/domain/entities/user.dart
  metrics/web/lib/auth/domain/usecases/parameters/user_credentials_param.dart
  metrics/web/lib/auth/presentation/strings/auth_strings.dart
  metrics/web/lib/base/domain/usecases/usecase.dart
  metrics/web/lib/base/presentation/decoration/bubble_shape_border.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_field_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/delete_dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_widget_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/toggle/widgets/toggle.dart
  metrics/web/lib/dashboard/domain/entities/collections/date_time_set_entry.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_number_metric.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_performance.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_result.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_result_metric.dart
  metrics/web/lib/dashboard/domain/entities/metrics/builds_on_date.dart
  metrics/web/lib/dashboard/domain/entities/metrics/performance_metric.dart
  metrics/web/lib/dashboard/domain/usecases/parameters/project_id_param.dart
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/widgets/no_data_placeholder.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/metrics_value_style_strategy.dart
  metrics/web/lib/main.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
Labels: size/L

#684 docs: Improve GitHub Actions document
  metrics/ci_integrations/docs/github_actions/01_github_actions_client.md
  metrics/ci_integrations/docs/github_actions/diagrams/github_actions_client_class_diagram.puml
Labels: size/L

#686 feat: Redesign the dashboard popup.
  metrics/web/lib/base/presentation/graphs/bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
  metrics/web/lib/main.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/graphs/bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
Labels: size/L

#680 ci: Implement GitHub Actions Client
  metrics/ci_integrations/lib/client/github_actions/constants/github_actions_constants.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/models/page.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_artifacts_page.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_runs_page.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/util/url/url_utils.dart
  metrics/ci_integrations/lib/util/validator/string_validator.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/github_actions/models/page_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_artifact_page_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_runs_page_test.dart
  metrics/ci_integrations/test/util/validator/string_validator_test.dart
Labels: size/XL

#694 test: Add tests to dashboard popup (theme).
  metrics/web/test/common/presentation/colored_bar/theme/attention_level/metrics_colored_bar_attention_level_test.dart
  metrics/web/test/common/presentation/colored_bar/theme/style/metrics_colored_bar_style_test.dart
  metrics/web/test/common/presentation/colored_bar/theme/theme_data/metrics_colored_bar_theme_data_test.dart
  metrics/web/test/common/presentation/graph_indicator/theme/attention_level/graph_indicator_attention_level_test.dart
  metrics/web/test/common/presentation/graph_indicator/theme/style/graph_indicator_style_test.dart
  metrics/web/test/common/presentation/graph_indicator/theme/theme_data/graph_indicator_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
Labels: size/L

#629 feat: metrics deploy command
  metrics/deploy/.gitignore
  metrics/deploy/CHANGELOG.md
  metrics/deploy/Makefile
  metrics/deploy/README.md
  metrics/deploy/analysis_options.yaml
  metrics/deploy/bin/main.dart
  metrics/deploy/coverage.sh
  metrics/deploy/docs/01_deploy_command.md
  metrics/deploy/lib/cli/firebase/firebase_command.dart
  metrics/deploy/lib/cli/gcloud/gcloud_command.dart
  metrics/deploy/lib/cli/git/git_command.dart
  metrics/deploy/lib/deploy/deploy_command.dart
  metrics/deploy/lib/doctor/doctor_command.dart
  metrics/deploy/pubspec.lock
  metrics/deploy/pubspec.yaml
  metrics/deploy/test.sh
  metrics/deploy/test/deploy/deploy_command_test.dart
  metrics/deploy/test/doctor/doctor_command_test.dart
  metrics/web/pubspec.lock
Labels: size/XXL

#701 test: Add tests to dashboard popup (widgets).
  metrics/web/lib/base/presentation/widgets/base_popup.dart
  metrics/web/lib/base/presentation/widgets/circle_graph_indicator.dart
  metrics/web/lib/common/presentation/colored_bar/widgets/metrics_colored_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/test/base/presentation/graphs/bar_graph_test.dart
  metrics/web/test/base/presentation/widgets/base_popup_test.dart
  metrics/web/test/base/presentation/widgets/circle_graph_indicator_test.dart
  metrics/web/test/common/presentation/colored_bar/widgets/metrics_colored_bar_test.dart
  metrics/web/test/common/presentation/graph_indicator/widgets/graph_indicator_test.dart
  metrics/web/test/common/presentation/graph_indicator/widgets/negative_graph_indicator_test.dart
  metrics/web/test/common/presentation/graph_indicator/widgets/neutral_graph_indicator_test.dart
  metrics/web/test/common/presentation/graph_indicator/widgets/positive_graph_indicator_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_popup_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy_test.dart
Labels: size/XXL

#700 feat: Implement Github Actions Source Config Parser
  metrics/ci_integrations/docs/github_actions/config/configuration_template.yaml
  metrics/ci_integrations/lib/source/github_actions/config/model/github_actions_source_config.dart
  metrics/ci_integrations/lib/source/github_actions/config/parser/github_actions_source_config_parser.dart
  metrics/ci_integrations/test/source/github_actions/config/model/github_actions_source_config_test.dart
  metrics/ci_integrations/test/source/github_actions/config/parser/github_actions_source_config_parser_test.dart
  metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_config_test_data.dart
Labels: size/L

#705 fix: Update chromedriver version to match latest Google Chrome
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: Snake 🐍, size/XS

#706 fix: Fix performance and builds metrics loading
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
Labels: Snake 🐍, size/S

#704 ci: Implement CI Integrations Actions
  .github/workflows/ci_integrations_actions.yml
  analysis_options.yaml
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/models/page.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_artifact.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_duration.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_build.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_build_artifact.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_building_job.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_job.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_multi_branch_job.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_query_limits.dart
  metrics/ci_integrations/lib/util/model/interaction_result.dart
  metrics/ci_integrations/test/cli/logger/logger_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/M

#711 fix: Fix circle percentage value text displaying
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/test/base/presentation/graphs/circle_percentage_test.dart
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: size/L

#710 fix: Fix the performance of the Dashboard page.
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
Labels: size/L

#693 docs: Coverage Converter design document
  metrics/ci_integrations/docs/01_ci_integration_module_architecture.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_coverage_class_diagram.puml
  metrics/coverage_converter/docs/01_coverage_converter_design.md
  metrics/coverage_converter/docs/diagrams/converter_exception_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_conversion_activity.puml
  metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml
Labels: size/L

#723 fix: Improve coverage converter diagrams
  metrics/ci_integrations/docs/diagrams/ci_integrations_coverage_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
Labels: size/S

#714 docs: Changes to the GitHub actions client design
  metrics/ci_integrations/docs/github_actions/01_github_actions_client.md
  metrics/ci_integrations/docs/github_actions/diagrams/github_actions_client_class_diagram.puml
Labels: size/L

#733 fix: Update chromedriver version
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: Snake 🐍, size/XS

#734 feat: Make driver tests script use installed web driver if any
  metrics/web/pubspec.lock
  metrics/web/pubspec.yaml
  metrics/web/test_driver/cli/web_driver/chrome_driver.dart
  metrics/web/test_driver/cli/web_driver/process/chrome_driver_process.dart
  metrics/web/test_driver/cli/web_driver/web_driver.dart
  metrics/web/test_driver/flutter_web_driver.dart
Labels: Snake 🐍, size/L

#702 feat: doctor command refactor
  metrics/deploy/lib/cli/firebase/firebase_command.dart
  metrics/deploy/lib/cli/flutter/flutter_command.dart
  metrics/deploy/lib/cli/gcloud/gcloud_command.dart
  metrics/deploy/lib/cli/git/git_command.dart
  metrics/deploy/lib/doctor/doctor_command.dart
Labels: size/M

#735 fix: Rename CoverageModel to CoverageData in the Coverage Converter design document and fix typos
  metrics/ci_integrations/docs/diagrams/ci_integrations_coverage_class_diagram.puml
  metrics/coverage_converter/docs/01_coverage_converter_design.md
  metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_conversion_activity.puml
  metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml
Labels: Snake 🐍, size/S

#715 fix: Fix user profile creation on opening the logged-in application
  metrics/web/lib/auth/presentation/pages/loading_page.dart
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/widgets/platform_brightness_observer.dart
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/widgets/platform_brightness_observer_test.dart
  metrics/web/test/test_utils/binding_util.dart
Labels: size/L

#724 feat: Change BuildStatus to include 3 states (success, failed, unknown)
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
  metrics/core/lib/src/data/model/build_data.dart
  metrics/core/lib/src/data/model/project_data.dart
  metrics/core/lib/src/domain/entities/build.dart
  metrics/core/lib/src/domain/entities/build_status.dart
  metrics/core/lib/src/domain/entities/project.dart
  metrics/core/test/data/model/build_data_test.dart
  metrics/web/lib/dashboard/data/deserializer/build_data_deserializer.dart
  metrics/web/lib/dashboard/domain/usecases/parameters/project_id_param.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/test/dashboard/data/deserializer/build_data_deserializer_test.dart
  metrics/web/test/dashboard/domain/entities/metrics/project_build_status_metric_test.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_build_status_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
Labels: size/L

#731 feat: Create the entity class and the data model
  metrics/ci_integrations/lib/coverage/coverage_json_summary/model/coverage_json_summary.dart
  metrics/ci_integrations/lib/coverage/coverage_json_summary/model/total_coverage_summary.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/coverage/coverage_json_summary_parser/model/coverage_json_summary_test.dart
  metrics/ci_integrations/test/coverage/coverage_json_summary_parser/model/coverage_test.dart
  metrics/ci_integrations/test/coverage/coverage_json_summary_parser/model/total_coverage_summary_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
  metrics/core/lib/metrics_core.dart
  metrics/core/lib/src/data/model/coverage_data.dart
  metrics/core/lib/src/domain/entities/coverage.dart
  metrics/core/test/data/model/coverage_data_test.dart
  metrics/core/test/domain/entities/coverage_test.dart
  metrics/core/test/domain/value_objects/percent_test.dart
  metrics/coverage_converter/lib/common/exception/coverage_converter_exception.dart
  metrics/coverage_converter/lib/common/exception/error_code/coverage_converter_error_code.dart
  metrics/coverage_converter/lib/common/strings/common_strings.dart
  metrics/coverage_converter/pubspec.yaml
  metrics/coverage_converter/test/common/exception/coverage_converter_exception_test.dart
Labels: size/L

#732 fix: Change Github Actions config
  metrics/ci_integrations/lib/source/github_actions/config/model/github_actions_source_config.dart
  metrics/ci_integrations/test/source/github_actions/config/model/github_actions_source_config_test.dart
  metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_config_test_data.dart
Labels: size/L

#722 fix: Update GitHub Actions Client according to the new design
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/mappers/github_action_conclusion_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/mappers/github_action_status_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/mappers/run_conclusion_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/mappers/run_status_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_action_conclusion.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_action_status.dart
  metrics/ci_integrations/lib/client/github_actions/models/run_conclusion.dart
  metrics/ci_integrations/lib/client/github_actions/models/run_status.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_duration.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_job.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_jobs_page.dart
  metrics/ci_integrations/test/client/github_actions/mappers/github_action_conclusion_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/mappers/github_action_status_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/mappers/run_conclusion_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/mappers/run_status_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_artifact_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_duration_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_job_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_jobs_page_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
Labels: size/XXL

#737 docs: Add design first and design documentation sections, move bash scripts
  docs/02_process.md
Labels: size/M

#713 feat: Coverage converter publishing/usage document
  metrics/coverage_converter/docs/02_coverage_converter_publishing.md
Labels: size/L

#740 feat: Improve coverage arguments parsing design
  metrics/coverage_converter/docs/01_coverage_converter_design.md
  metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml
Labels: Snake 🐍, size/L

#744 docs: Minor improvements in metrics descriptions
  docs/05_project_metrics.md
  docs/images/placeholder.png
  docs/images/placeholder_light.png
Labels: Snake 🐍, size/S

#743 feat: Coverage converter arguments parser and runner
  metrics/coverage_converter/bin/main.dart
  metrics/coverage_converter/lib/common/arguments/model/coverage_converter_arguments.dart
  metrics/coverage_converter/lib/common/arguments/parser/arguments_parser.dart
  metrics/coverage_converter/lib/common/arguments/parser/coverage_converter_arguments_parser.dart
  metrics/coverage_converter/lib/common/runner/coverage_converter_runner.dart
  metrics/coverage_converter/pubspec.yaml
  metrics/coverage_converter/test/common/arguments/model/coverage_converter_arguments_test.dart
  metrics/coverage_converter/test/common/arguments/parser/arguments_parser_test.dart
  metrics/coverage_converter/test/common/arguments/parser/coverage_converter_arguments_parser_test.dart
  metrics/coverage_converter/test/common/runner/coverage_converter_runner_test.dart
Labels: size/L

#736 feat: Implement Github Actions Source Client Adapter
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/util/archive/archive_helper.dart
  metrics/ci_integrations/pubspec.yaml
  metrics/ci_integrations/test/util/archive/archive_helper_test.dart
Labels: size/L

#741 feat: Update dashboard popup to include build status
  metrics/web/lib/auth/domain/usecases/parameters/user_profile_param.dart
  metrics/web/lib/common/presentation/colored_bar/theme/style/metrics_colored_bar_style.dart
  metrics/web/lib/common/presentation/colored_bar/widgets/metrics_colored_bar.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/value_image/strategy/value_based_image_asset_strategy.dart
  metrics/web/lib/common/presentation/value_image/widgets/value_network_image.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_popup_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_popup_card.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_status_style_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/test/common/presentation/colored_bar/theme/style/metrics_colored_bar_style_test.dart
  metrics/web/test/common/presentation/colored_bar/widgets/metrics_colored_bar_test.dart
  metrics/web/test/common/presentation/metrics_theme/state/theme_notifier_test.dart
  metrics/web/test/common/presentation/value_image/widgets/value_network_image_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_popup_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart
  metrics/web/test/dashboard/presentation/widgets/coverage_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/stability_circle_percentage_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
  metrics/web/test/test_utils/auth_notifier_mock.dart
  metrics/web/test/test_utils/theme_notifier_mock.dart
  metrics/web/web/icons/failed.svg
  metrics/web/web/icons/failed_status.svg
  metrics/web/web/icons/successful.svg
  metrics/web/web/icons/unknown.svg
Labels: size/XXL

#742 docs: Create Buildkite REST API Client Design document.
  metrics/ci_integrations/docs/buildkite/01_buildkite_client.md
  metrics/ci_integrations/docs/buildkite/diagrams/buildkite_client_class_diagram.puml
Labels: size/L

#748 feat: Integrate Github Actions Source Client to CLI
  metrics/ci_integrations/lib/cli/parties/supported_source_parties.dart
  metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/test/cli/parties/supported_source_parties_test.dart
  metrics/ci_integrations/test/source/github_actions/client_factory/github_actions_source_client_factory_test.dart
  metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart
Labels: size/L

#745 feat: Coverage converter main abstract classes and interfaces
  metrics/coverage_converter/lib/common/command/coverage_converter_command.dart
  metrics/coverage_converter/lib/common/converter/coverage_converter.dart
  metrics/coverage_converter/lib/common/exception/coverage_converter_exception.dart
  metrics/coverage_converter/pubspec.yaml
  metrics/coverage_converter/test/common/command/coverage_converter_command_test.dart
  metrics/coverage_converter/test/common/exception/coverage_converter_exception_test.dart
  metrics/coverage_converter/test/utils/file_mock.dart
Labels: size/L

#749 chore: update github templates to improve process
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/pull_request_template.md
Labels: Snake 🐍, size/S

#747 feat: Coverage Converter: setup macOS, linux publishing
  .github/workflows/coverage_converter_actions.yml
Labels: size/L

#751 test: Implement GitHub Actions Mock Server
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
Labels: size/L

#758 feat: Implement Buildkite client mappers.
  metrics/ci_integrations/lib/client/buildkite/mappers/buildkite_build_state_mapper.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_build_state.dart
  metrics/ci_integrations/test/client/buildkite/mappers/buildkite_build_state_mapper_test.dart
Labels: size/L

#760 test: Add tests for the github actions client
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
Labels: size/XL

#759 docs: CoverageConverter design improvement
  metrics/coverage_converter/docs/01_coverage_converter_design.md
  metrics/coverage_converter/docs/diagrams/converter_exception_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_conversion_activity.puml
  metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
  metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml
Labels: Snake 🐍, size/M
