Repository Flank/flank-dashboard, pull requests merged in 2020-06, with the labels that each got.

#236 Add PR limits and guidelines
  docs/02_process.md
Labels: size/S

#237 GitHub actions configuration
  .github/workflows/web_app_test_and_deploy.yml
Labels: size/M

#250 Fix GitHub Actions trigger
  .github/workflows/web_app_actions.yml
Labels: size/S

#253 Apply github action trigger to all metrics web application directories
  .github/workflows/web_app_actions.yml
Labels: size/XS

#265 Project Group Card theme
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_card_theme_data.dart
  metrics/web/lib/main.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_card_theme_data_test.dart
Labels: size/L

#262 Make sparkline graph match new architecture
  .github/workflows/web_app_actions.yml
  metrics/web/lib/base/presentation/graphs/sparkline_graph.dart
  metrics/web/lib/dashboard/presentation/models/project_metrics_data.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/performance_sparkline_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/sparkline_graph.dart
  metrics/web/test/base/presentation/graphs/sparkline_graph_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/performance_sparkline_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/sparkline_graph_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/XXL

#267 Project Group Card new design
  metrics/web/lib/base/presentation/widgets/icon_label_button.dart
  metrics/web/lib/base/presentation/widgets/padded_card.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
  metrics/web/pubspec.lock
  metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
  metrics/web/web/icons/add-button.svg
Labels: size/XL

#269 Improve firebase error handling
  metrics/web/lib/common/data/repositories/firestore_project_repository.dart
  metrics/web/lib/common/domain/entities/firestore_error_code.dart
  metrics/web/lib/common/domain/entities/firestore_exception.dart
  metrics/web/lib/common/domain/entities/persistent_store_error_code.dart
  metrics/web/lib/common/domain/entities/persistent_store_exception.dart
  metrics/web/lib/common/presentation/models/persistent_store_error_message.dart
  metrics/web/lib/common/presentation/state/projects_notifier.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/project_groups/data/repositories/firestore_project_group_repository.dart
  metrics/web/lib/project_groups/presentation/models/project_group_firestore_error_message.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/test/common/domain/entities/firestore_exception_test.dart
  metrics/web/test/common/domain/entities/persistent_store_exception_test.dart
  metrics/web/test/common/presentation/models/persistent_store_error_message_test.dart
  metrics/web/test/project_groups/presentation/models/project_group_firestore_error_message_test.dart
Labels: size/L

#272 Remove GitHub action job name
  .github/workflows/web_app_actions.yml
Labels: size/XS

#271 Improve build number metric to fit the new architecture
  metrics/web/lib/base/presentation/widgets/scorecard.dart
  metrics/web/lib/dashboard/presentation/models/project_metrics_data.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_number_scorecard_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_number_scorecard.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/base/presentation/widgets/scorecard_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_number_scorecard_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_number_text_metric_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
  metrics/web/test_driver/app_test.dart
Labels: size/L

#276 Add more tests for common/presentation package
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
  metrics/web/test/common/presentation/widgets/metrics_text_placeholder_test.dart
Labels: size/L

#274 Add the hover effect
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/test/project_groups/presentation/project_group_card_test.dart
Labels: size/L
