Repository Flank/flank-dashboard, pull requests merged in 2020-11, with the labels that each got.

#752 feat: Implement LCOV coverage converter
  metrics/core/lib/src/data/model/coverage_data.dart
  metrics/core/lib/src/domain/entities/coverage.dart
  metrics/core/test/data/model/coverage_data_test.dart
  metrics/core/test/domain/entities/coverage_test.dart
  metrics/coverage_converter/lib/common/command/coverage_converter_command.dart
  metrics/coverage_converter/lib/common/converter/coverage_converter.dart
  metrics/coverage_converter/lib/common/exception/coverage_converter_exception.dart
  metrics/coverage_converter/lib/common/runner/coverage_converter_runner.dart
  metrics/coverage_converter/lib/lcov/command/lcov_coverage_converter_command.dart
  metrics/coverage_converter/lib/lcov/converter/lcov_coverage_converter.dart
  metrics/coverage_converter/pubspec.yaml
  metrics/coverage_converter/test/common/command/coverage_converter_command_test.dart
  metrics/coverage_converter/test/common/exception/coverage_converter_exception_test.dart
  metrics/coverage_converter/test/common/runner/coverage_converter_runner_test.dart
  metrics/coverage_converter/test/lcov/command/lcov_coverage_converter_command_test.dart
  metrics/coverage_converter/test/lcov/converter/lcov_coverge_converter_test.dart
Labels: size/L

#746 test: Implement Github Actions Source Client Adapter Tests
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/util/archive/archive_helper.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_test_data_generator.dart
  metrics/ci_integrations/test/util/archive/archive_helper_test.dart
Labels: size/XXL

#770 feat: Improve GitHub actions
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/firebase_actions.yml
  .github/workflows/metrics_actions.yml
  .github/workflows/web_actions.yml
Labels: size/L

#768 feat: Svg image with skia
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/sign_in_option_button.dart
  metrics/web/lib/base/presentation/widgets/svg_image.dart
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/user_menu_button/widgets/metrics_user_menu_button.dart
  metrics/web/lib/common/presentation/value_image/widgets/value_network_image.dart
  metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
  metrics/web/lib/common/presentation/widgets/metrics_theme_image.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/lib/dashboard/presentation/widgets/projects_search_input.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/util/web_platform.dart
  metrics/web/pubspec.lock
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/widgets/svg_image_test.dart
  metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
  metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
  metrics/web/test/test_utils/finder_util.dart
Labels: size/XL

#769 feat: Implement Buildkite client.
  metrics/ci_integrations/docs/buildkite/diagrams/buildkite_client_class_diagram.puml
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/buildkite/constants/buildkite_constants.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_artifact.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_build.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_artifact_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_artifacts_page_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_build_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_builds_page_test.dart
Labels: size/XL

#772 fix: Fix GitHub Actions triggers
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/web_actions.yml
Labels: Snake 🐍, size/XS

#771 feat: Buildkite YAML config and config parser
  metrics/ci_integrations/docs/buildkite/config/configuration_template.yaml
  metrics/ci_integrations/lib/source/buildkite/config/model/buildkite_source_config.dart
  metrics/ci_integrations/lib/source/buildkite/config/parser/buildkite_source_config_parser.dart
  metrics/ci_integrations/test/source/buildkite/config/model/buildkite_source_config_test.dart
  metrics/ci_integrations/test/source/buildkite/config/parser/buildkite_source_config_parser_test.dart
  metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_config_test_data.dart
Labels: size/L

#775 fix: Fix GitHub coverage fetching and Coverage data model
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/web_actions.yml
  metrics/core/lib/src/data/model/coverage_data.dart
  metrics/core/test/data/model/coverage_data_test.dart
Labels: size/S

#776 fix: Add test coverage dependency to the coverage converter
  metrics/coverage_converter/pubspec.yaml
Labels: Snake 🐍, size/XS

#777 fix: URLs in models must link to Github web
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run_job.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_job_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
Labels: Snake 🐍, size/S

#781 fix: Fix the UserMenuTheme and ToggleTheme.
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
Labels: size/M

#780 feat: Create adapter for Buildkite client.
  metrics/ci_integrations/docs/01_ci_integration_module_architecture.md
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
Labels: size/L

#788 feat: Add metrics integration GitHub action
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/metrics_integration_actions.yml
  .github/workflows/web_actions.yml
  .metrics/ci_integrations_config.yml
  .metrics/coverage_converter_config.yml
  .metrics/metrics_web_config.yml
Labels: size/L

#774 test: Buildkite mock server
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
  metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
  metrics/ci_integrations/test/client/test_utils/mock_server_utils.dart
Labels: size/L

#795 fix: Rename firebase API key to the firebase public API key.
  .metrics/ci_integrations_config.yml
  .metrics/coverage_converter_config.yml
  .metrics/metrics_web_config.yml
  metrics/ci_integrations/config.yaml
  metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
  metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config.dart
  metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
  metrics/ci_integrations/test/destination/firestore/config/model/firestore_destination_config_test.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/test_data/firestore_config_test_data.dart
Labels: size/M

#794 fix: Update build statuses in firebase
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/functions/index.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: Snake 🐍, size/XS

#799 fix: Override the `coverage` dependency to use the latest version from the GitHub
  metrics/ci_integrations/pubspec.yaml
  metrics/coverage_converter/pubspec.yaml
Labels: Snake 🐍, size/S

#796 feat: Integrate Adapter/SourceClient to CI Integrations
  metrics/ci_integrations/lib/cli/parties/supported_source_parties.dart
  metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
  metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
  metrics/ci_integrations/test/cli/parties/supported_source_parties_test.dart
  metrics/ci_integrations/test/source/buildkite/client_factory/buildkite_source_client_factory_test.dart
  metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart
Labels: size/L

#800 fix: Fix test_coverage dependency to be compatible with latest coverage package
  metrics/ci_integrations/pubspec.yaml
  metrics/coverage_converter/pubspec.yaml
Labels: Snake 🐍, size/S

#801 fix: Update Ci Integrations link to point to latest version
  .github/workflows/metrics_integration_actions.yml
Labels: Snake 🐍, size/XS

#792 feat: Configure github actions to run tests and linter for metrics core module
  .github/workflows/metrics_actions.yml
Labels: size/M

#791 test: Create tests for Buildkite Adapter
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/test_utils/extensions/interaction_result_answer.dart
Labels: size/XXL

#793 test: Buildkite client tests
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
Labels: size/L

#802 ci: Add newlines, fix interpolation in Buildkite pipelines
  .buildkite/pipelines/ci_integrations_pipeline.yml
  .buildkite/pipelines/metrics_web_pipeline.yml
Labels: Snake 🐍, size/XS

#804 feat: Configure CI Integrations publishing GitHub Actions
  .github/workflows/ci_integrations_actions.yml
Labels: size/L

#806 feat: Update `test_coverage` and `coverage` packages versions to latest
  metrics/ci_integrations/pubspec.yaml
  metrics/coverage_converter/pubspec.yaml
Labels: Snake 🐍, size/S

#807 feat: Update CI Integrations links to point to GitHub releases
  .github/workflows/metrics_integration_actions.yml
Labels: Snake 🐍, size/XS

#813 fix: Fix CI Integrations linux asset name
  .github/workflows/ci_integrations_actions.yml
Labels: Snake 🐍, size/XS

#814 test: Update Driver Tests
  metrics/web/test_driver/cli/web_driver/chrome_driver.dart
  metrics/web/test_driver/common/config/driver_tests_config.dart
  metrics/web/test_driver/flutter_web_driver.dart
Labels: Snake 🐍, size/M

#797 ci: Implement links checker and create new github actions job
  .github/pull_request_template.md
  .github/workflows/metrics_actions.yml
  scripts/links_checker/analysis_options.yaml
  scripts/links_checker/bin/main.dart
  scripts/links_checker/lib/arguments/models/links_checker_arguments.dart
  scripts/links_checker/lib/arguments/parser/links_checker_arguments_parser.dart
  scripts/links_checker/lib/checker/links_checker.dart
  scripts/links_checker/lib/command/links_checker_command.dart
  scripts/links_checker/lib/exception/links_checker_exception.dart
  scripts/links_checker/lib/runner/links_checker_runner.dart
  scripts/links_checker/lib/utils/file_helper_util.dart
  scripts/links_checker/pubspec.yaml
  scripts/links_checker/test/arguments/models/links_checker_arguments_tests.dart
  scripts/links_checker/test/arguments/parser/links_checker_arguments_parser_test.dart
  scripts/links_checker/test/checker/links_checker_test.dart
  scripts/links_checker/test/command/links_checker_command_test.dart
  scripts/links_checker/test/exception/links_checker_exception_test.dart
  scripts/links_checker/test/runner/links_checker_runner_test.dart
Labels: size/XL

#817 feat: Treat timeout as failed
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
Labels: size/S

#815 docs: Create dependencies licenses document
  docs/16_dependencies_licenses.md
Labels: size/L

#822 fix: Update Chrome driver version
  metrics/web/test_driver/common/config/driver_tests_config.dart
Labels: Snake 🐍, size/XS

#820 feat: Skia deployment - enable auto renderer
  .github/workflows/web_actions.yml
  docs/16_dependencies_licenses.md
  metrics/web/lib/util/web_platform.dart
  metrics/web/pubspec.lock
  metrics/web/pubspec.yaml
Labels: size/L

#821 feat: [CI Integrations] Default values for BuildData
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/L

#826 docs: Update Email value object documentation
  metrics/core/lib/src/domain/value_objects/email.dart
Labels: Snake 🐍, size/XS

#835 docs: Firebase key restrictions
  .github/workflows/metrics_integration_actions.yml
  .metrics/buildkite/integration_config.yml
  .metrics/ci_integrations_config.yml
  .metrics/coverage_converter_config.yml
  .metrics/metrics_web_config.yml
  docs/09_firebase_deployment.md
Labels: size/M

#836 feat: Implement Tooltip Popup theme
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/tooltip_icon/theme/theme_data/tooltip_icon_theme_data.dart
  metrics/web/lib/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/tooltip_icon/theme/theme_data/tooltip_icon_theme_data_test.dart
  metrics/web/test/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data_test.dart
Labels: size/L

#838 docs: Create Firebase analytics design document
  metrics/web/docs/features/firebase_analytics/01_firebase_analytics_design.md
  metrics/web/docs/features/firebase_analytics/diagrams/firebase_analytics_data_class.puml
  metrics/web/docs/features/firebase_analytics/diagrams/firebase_analytics_domain_class.puml
  metrics/web/docs/features/firebase_analytics/diagrams/firebase_analytics_log_login_sequence.puml
  metrics/web/docs/features/firebase_analytics/diagrams/firebase_analytics_log_page_view_sequence.puml
  metrics/web/docs/features/firebase_analytics/diagrams/firebase_analytics_presentation.puml
  metrics/web/docs/features/user_profile_theme/diagrams/user_profile_theme_domain_class.puml
Labels: size/L

#844 feat: Improve test driver to be able to run in docker
  metrics/web/test_driver/arguments/model/driver_test_arguments.dart
  metrics/web/test_driver/arguments/parser/driver_test_arguments_parser.dart
  metrics/web/test_driver/cli/flutter/command/run_command.dart
  metrics/web/test_driver/cli/flutter/command/run_command_base.dart
  metrics/web/test_driver/cli/flutter/model/flutter_drive_environment.dart
  metrics/web/test_driver/cli/flutter/runner/flutter_drive_process_runner.dart
  metrics/web/test_driver/cli/flutter/runner/flutter_run_process_runner.dart
  metrics/web/test_driver/common/config/logs_file_config.dart
  metrics/web/test_driver/flutter_web_driver.dart
Labels: Snake 🐍, size/L

#848 fix: Change the diagrams links to master
  metrics/web/docs/features/firebase_analytics/01_firebase_analytics_design.md
Labels: Snake 🐍, size/S

#840 test: Driver tests improvements
  metrics/web/test_driver/arguments/model/driver_test_arguments.dart
  metrics/web/test_driver/arguments/parser/driver_test_arguments_parser.dart
  metrics/web/test_driver/cli/web_driver/chrome_driver.dart
  metrics/web/test_driver/cli/web_driver/web_driver.dart
  metrics/web/test_driver/common/config/driver_tests_config.dart
  metrics/web/test_driver/flutter_web_driver.dart
  metrics/web/test_driver/util/chrome_driver_utils.dart
Labels: size/L

#839 docs: Design document for the Remote Config
  metrics/web/docs/features/remote_config/01_remote_config_design.md
  metrics/web/docs/features/remote_config/diagrams/remote_config_data_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_domain_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_presentation_layer_class_diagram.puml
  metrics/web/docs/features/remote_config/diagrams/remote_config_sequence_diagram.puml
Labels: size/L
