Repository Flank/flank-dashboard, pull requests merged in 2020-07, with the labels that each got.

#279 Fix project metrics subscriptions
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/L

#282 add tests for the projects notifier and project model
  metrics/web/lib/common/presentation/models/project_model.dart
  metrics/web/test/common/presentation/models/project_model_test.dart
  metrics/web/test/common/presentation/state/projects_notifier_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
Labels: size/L

#286 Project metrics tile view model
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/project_metrics_tile_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/L

#284 Introduce reusable dialog strategy
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/view_models/delete_project_group_dialog_view_model.dart
  metrics/web/lib/project_groups/presentation/view_models/project_group_delete_dialog_view_model.dart
  metrics/web/lib/project_groups/presentation/view_models/project_group_dialog_view_model.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/edit_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/project_group_dialog_strategy.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/edit_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy_test.dart
  metrics/web/test/test_utils/project_groups_notifier_mock.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/XL

#293 Change the application font family
  metrics/web/lib/main.dart
  metrics/web/pubspec.yaml
Labels: size/S

#290 Improve auth module to match new architecture
  metrics/web/lib/auth/presentation/models/auth_error_message.dart
  metrics/web/lib/auth/presentation/models/email_validation_error_message.dart
  metrics/web/lib/auth/presentation/models/password_validation_error_message.dart
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/auth/presentation/widgets/auth_input_field.dart
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/auth/presentation/widgets/auth_input_field_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/L

#300 Improve view model management in ProjectGroupsNotifier
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy.dart
Labels: size/L

#302 Make project group view models equatable
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/view_models/project_checkbox_view_model.dart
  metrics/web/lib/project_groups/presentation/view_models/project_group_card_view_model.dart
  metrics/web/lib/project_groups/presentation/view_models/project_group_dialog_view_model.dart
  metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart
Labels: size/M

#307 View models immutability improvements
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_number_scorecard_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/performance_sparkline_view_model.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/lib/project_groups/presentation/view_models/delete_project_group_dialog_view_model.dart
  metrics/web/lib/project_groups/presentation/view_models/project_group_dialog_view_model.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/performance_sparkline_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/edit_project_group_dialog_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/L

#297 Scaffold design improvements
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/pubspec.lock
  metrics/web/test/auth/presentation/pages/loading_page_test.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/drawer/widget/metrics_drawer_test.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
  metrics/web/test/common/presentation/widgets/metrics_page_title_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test_driver/app_test.dart
  metrics/web/web/icons/arrow-back.svg
  metrics/web/web/icons/avatar.svg
  metrics/web/web/icons/logo-metrics.svg
Labels: size/XL

#311 Add the app icon navigation. Add tests.
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/widgets/metrics_page_title_test.dart
Labels: size/M

#304 Add tests for project groups notifier
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart
Labels: size/XXL

#312 Minor enhancements to metrics deployment documentation
  docs/09_firebase_deployment.md
Labels: size/XS

#314 Tests for ProjectGroupsPage class
  metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
  metrics/web/test/test_utils/metrics_themed_testbed.dart
  metrics/web/test/test_utils/projects_notifier_stub.dart
Labels: size/L

#316 Project groups validator name and strings tests
  metrics/web/test/project_groups/presentation/strings/project_groups_strings_test.dart
  metrics/web/test/project_groups/presentation/validators/project_group_name_validator_test.dart
Labels: size/M

#309 Create the project group dialog theme
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_field_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/main.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dialog_theme_data_test.dart
Labels: size/L

#320 Project groups view models tests
  metrics/web/lib/project_groups/presentation/view_models/delete_project_group_dialog_view_model.dart
  metrics/web/test/project_groups/presentation/view_models/delete_project_group_dialog_view_model_test.dart
  metrics/web/test/project_groups/presentation/view_models/project_checkbox_view_model_test.dart
  metrics/web/test/project_groups/presentation/view_models/project_group_card_view_model_test.dart
  metrics/web/test/project_groups/presentation/view_models/project_group_dialog_view_model_test.dart
Labels: size/L

#318 Improve documentation to include the information about immutable classes
  docs/10_dart_code_style.md
  metrics/web/docs/03_widget_structure_organization.md
Labels: size/L

#322 Add base dropdown menu widget
  metrics/web/lib/base/presentation/widgets/dropdown_menu.dart
  metrics/web/pubspec.lock
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/widgets/dropdown_menu_test.dart
Labels: size/XL

#323 Change cursor for tappable widgets
  metrics/web/lib/auth/presentation/widgets/auth_form.dart
  metrics/web/lib/base/presentation/widgets/clearable_text_form_field.dart
  metrics/web/lib/base/presentation/widgets/hand_cursor.dart
  metrics/web/lib/base/presentation/widgets/icon_label_button.dart
  metrics/web/lib/base/presentation/widgets/info_dialog.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/drawer/widget/metrics_drawer.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/pubspec.yaml
  metrics/web/test/auth/presentation/widgets/auth_form_test.dart
  metrics/web/test/base/presentation/widgets/clearable_text_form_field_test.dart
  metrics/web/test/base/presentation/widgets/hand_cursor_test.dart
  metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
  metrics/web/test/base/presentation/widgets/info_dialog_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/drawer/widget/metrics_drawer_test.dart
  metrics/web/test/common/presentation/widgets/metrics_page_title_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/edit_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/web/index.html
Labels: size/XL

#327 Tests for project group cards
  metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
Labels: size/XL

#330 Project groups dropdown ui
  .github/workflows/web_app_actions.yml
  metrics/web/lib/base/presentation/widgets/dropdown_body.dart
  metrics/web/lib/base/presentation/widgets/dropdown_item.dart
  metrics/web/lib/base/presentation/widgets/dropdown_menu.dart
  metrics/web/lib/common/presentation/constants/duration_constants.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/project_group_dropdown_item_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_item.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/pubspec.lock
  metrics/web/test/base/presentation/widgets/dropdown_menu_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
  metrics/web/web/icons/dropdown.svg
Labels: size/XL

#342 Add tests for base dropdown widgets
  metrics/web/test/base/presentation/widgets/dropdown_body_test.dart
  metrics/web/test/base/presentation/widgets/dropdown_item_test.dart
Labels: size/L

#331 Readme update
  concept_map.puml
  metrics/web/README.md
  readme.md
Labels: size/L

#343 Create reusable Metrics buttons
  metrics/web/lib/common/presentation/button/theme/attention_level/metrics_button_attention_level.dart
  metrics/web/lib/common/presentation/button/theme/style/metrics_button_style.dart
  metrics/web/lib/common/presentation/button/theme/theme_data/metrics_button_theme_data.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_button.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_negative_button.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_neutral_button.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_positive_button.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/attention_level_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/test/common/presentation/button/theme/attention_level/metrics_button_attention_level_test.dart
  metrics/web/test/common/presentation/button/theme/style/metrics_button_style_test.dart
  metrics/web/test/common/presentation/button/theme/theme_data/metrics_button_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
Labels: size/L

#345 Create reusable Metrics text fields
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_field_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/text_field_theme_data.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/main.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/text_field_theme_data_test.dart
Labels: size/L

#344 Add tests for project groups dropdown ui widgets
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_group_dropdown_item_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_item_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
Labels: size/XL

#349 Create theme data for project groups dropdown
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_groups_dropdown_item_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_groups_dropdown_theme_data.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dropdown_item_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dropdown_theme_data_test.dart
Labels: size/L

#351 Add tests for Metrics buttons
  metrics/web/test/common/presentation/button/widgets/metrics_button_test.dart
  metrics/web/test/common/presentation/button/widgets/metrics_negative_button_test.dart
  metrics/web/test/common/presentation/button/widgets/metrics_neutral_button_test.dart
  metrics/web/test/common/presentation/button/widgets/metrics_positive_button_test.dart
Labels: size/L

#346 Update metrics loading
  metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
  metrics/web/lib/dashboard/domain/entities/metrics/project_build_status_metric.dart
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
  metrics/web/test/dashboard/domain/entities/metrics/project_build_status_metric_test.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
  metrics/web/test_driver/app_test.dart
Labels: size/L

#325 Apply dialog theme data.
  metrics/web/lib/base/presentation/widgets/clearable_text_form_field.dart
  metrics/web/lib/base/presentation/widgets/info_dialog.dart
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/lib/main.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/base/presentation/widgets/clearable_text_form_field_test.dart
  metrics/web/test/base/presentation/widgets/info_dialog_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dialog_theme_data_test.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/edit_project_group_dialog_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/test/test_utils/metrics_themed_testbed.dart
  metrics/web/web/icons/close.svg
  metrics/web/web/icons/search.svg
Labels: size/XL

#353 Add tests for project groups widgets
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_view_test.dart
  metrics/web/test/test_utils/project_groups_notifier_stub.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/XL

#355 Update ProjectMetricsTile widget layout
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/test_utils/dimensions_util.dart
Labels: size/XL

#357 Apply theme for project groups dropdown widgets
  metrics/web/lib/base/presentation/widgets/dropdown_item.dart
  metrics/web/lib/base/presentation/widgets/dropdown_menu.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dropdown_item_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dropdown_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_groups_dropdown_item_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_groups_dropdown_theme_data.dart
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_item.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/test/base/presentation/widgets/dropdown_item_test.dart
  metrics/web/test/base/presentation/widgets/dropdown_menu_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dropdown_item_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dropdown_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_item_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
Labels: size/XL

#363 Add tests for the Metrics text field
  metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
  metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
  metrics/web/test/test_utils/metrics_themed_testbed.dart
Labels: size/L

#365 Bar graph and placeholder bar changes
  metrics/web/lib/base/presentation/graphs/bar_graph.dart
  metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/test/base/presentation/graphs/placeholder_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
Labels: size/M

#359 Change delete dialog appearance
  metrics/web/lib/base/presentation/widgets/info_dialog.dart
  metrics/web/lib/common/presentation/button/theme/style/metrics_button_style.dart
  metrics/web/lib/common/presentation/button/widgets/metrics_button.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/delete_dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
  metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
  metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
  metrics/web/test/base/presentation/widgets/info_dialog_test.dart
  metrics/web/test/common/presentation/button/theme/style/metrics_button_style_test.dart
  metrics/web/test/common/presentation/button/widgets/metrics_button_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/delete_dialog_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/project_groups/presentation/strings/project_groups_strings_test.dart
  metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
Labels: size/XL

#369 Project build status widget
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/project_build_status_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/project_metrics_tile_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_build_status_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/test_utils/finder_util.dart
  metrics/web/web/icons/failed_status.svg
  metrics/web/web/icons/successful_status.svg
  metrics/web/web/icons/unknown_status.svg
Labels: size/L

#367 Project group dropdown logic
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_item.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
  metrics/web/lib/project_groups/presentation/models/project_group_model.dart
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
  metrics/web/test/project_groups/presentation/models/project_group_model_test.dart
  metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
  metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart
  metrics/web/test/test_utils/project_groups_notifier_stub.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/XL

#371 Change projects checkbox list appearance
  metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list.dart
  metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
  metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
  metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
  metrics/web/web/icons/check-box-blank.svg
  metrics/web/web/icons/check-box.svg
Labels: size/L

#372 Create the login theme data for the Login page
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/main.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/login_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_group_dialog_theme_data_test.dart
  metrics/web/web/icons/logo-google.svg
Labels: size/L

#374 Improve circle percentage widgets to match new designs
  metrics/web/lib/base/presentation/graphs/circle_percentage.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/themed_circle_percentage.dart
Labels: size/S
