Repository Flank/flank-dashboard, pull requests merged in 2021-04, with the labels that each got.

#1252 fix: Fix package versions conflict on the latest master
  metrics/web/pubspec.yaml
Labels: Snake 🐍, size/XS

#1255 feat: Implement BuildResultBarComponent, update BuildResultBar
  metrics/web/lib/common/presentation/colored_bar/strategy/metrics_colored_bar_appearance_strategy.dart
  metrics/web/lib/common/presentation/graph_indicator/strategy/metrics_graph_indicator_appearance_strategy.dart
  metrics/web/lib/common/presentation/graph_indicator/widgets/metrics_graph_indicator.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_component.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_status_graph_indicator_appearance_strategy.dart
  metrics/web/test/common/presentation/graph_indicator/widgets/metrics_graph_indicator_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_component_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_status_graph_indicator_appearance_strategy_test.dart
Labels: size/XXL

#1251 feat: Implement BuildResultsMetricGraph
  metrics/web/docs/features/in_progress_builds/01_in_progress_builds_introduction.md
  metrics/web/docs/features/in_progress_builds/diagrams/presentation_layer_strategies_class_diagram.puml
  metrics/web/lib/base/presentation/graphs/bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/build_results_metric_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_duration_strategy.dart
  metrics/web/test/base/presentation/graphs/bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_results_metric_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_duration_strategy_test.dart
Labels: size/XXL

#1257 feat: Implement MetricsCliRunner
  docs/16_dependencies_licenses.md
  metrics/cli/bin/main.dart
  metrics/cli/lib/deploy/deploy_command.dart
  metrics/cli/lib/runner/metrics_cli_runner.dart
  metrics/cli/pubspec.yaml
  metrics/cli/test/deploy/deploy_command_test.dart
  metrics/cli/test/runner/metrics_cli_runner_test.dart
Labels: size/L

#1246 docs: Firestore emulator for driver tests design
  metrics/web/docs/analysis/02_firestore_emulator_for_driver_tests.md
  metrics/web/docs/features/firestore_emulator_for_driver_tests/01_firestore_emulator_for_driver_tests.md
  metrics/web/docs/features/firestore_emulator_for_driver_tests/diagrams/firestore_emulator_class_diagram.puml
  metrics/web/docs/features/firestore_emulator_for_driver_tests/diagrams/firestore_emulator_sequence_diagram.puml
Labels: size/L

#1256 feat: Add CLI commands error handling
  metrics/cli/lib/common/strings/common_strings.dart
  metrics/cli/lib/interfaces/cli/cli.dart
  metrics/cli/test/common/strings/common_strings_test.dart
  metrics/cli/test/flutter/adapter/flutter_cli_service_adapter_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
Labels: size/L

#1261 feat: Change BuildResultBarGraph and animate bars
  metrics/web/lib/common/presentation/widgets/timer_notifier_builder.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/test/common/presentation/widgets/timer_notifier_builder_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_results_metric_graph_test.dart
  metrics/web/test/test_utils/test_injection_container.dart
Labels: size/L

#1263 feat: Update Firestore rules for in-progress builds
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/builds-test.js
Labels: size/L

#1260 feat: Implement MetricsAnimatedBar
  metrics/web/lib/base/presentation/graphs/animated_bar.dart
  metrics/web/lib/base/presentation/widgets/rive_animation.dart
  metrics/web/lib/common/presentation/widgets/in_progress_animated_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/graphs/animated_bar_test.dart
  metrics/web/test/base/presentation/graphs/colored_bar_test.dart
  metrics/web/test/common/presentation/widgets/in_progress_animated_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_component_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_results_metric_graph_test.dart
  metrics/web/test/test_utils/presentation/widgets/rive_animation_testbed.dart
  metrics/web/test/test_utils/rive_asset_bundle_stub.dart
  metrics/web/web/animation/in_progress_bar.riv
  metrics/web/web/animation/in_progress_bar_hover.riv
Labels: Snake 🐍

#1265 feat: Extract DateRange widget
  metrics/web/lib/common/presentation/metrics_theme/model/build_result_bar_graph/theme_data/build_result_bar_graph_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/date_range/theme_data/date_range_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_group_card_theme_data.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/date_range_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_results_metric_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/date_range.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/date_range/theme_data/date_range_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/date_range_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_results_metric_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/date_range_test.dart
Labels: size/XL

#1266 docs: Cloud Functions using Dart Analysis doc
  metrics/firebase/docs/analysis/01_using_dart_in_the_firebase_cloud_functions.md
Labels: size/L

#1275 feat: Extend the BuildkiteClient to include the `fetchBuild` method
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
Labels: size/L

#1269 feat: Add the `in-progress-timeout` option to the Sync Command
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/integration/ci/config/model/sync_config.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
  metrics/ci_integrations/test/integration/ci/ci_integration_test.dart
  metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart
Labels: size/L

#1272 feat: Implement NpmService
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/common/model/services.dart
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/doctor/doctor.dart
  metrics/cli/lib/npm/adapter/npm_cli_service_adapter.dart
  metrics/cli/lib/npm/service/npm_service.dart
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/services_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deployer_factory_test.dart
  metrics/cli/test/doctor/doctor_test.dart
  metrics/cli/test/doctor/factory/doctor_factory_test.dart
  metrics/cli/test/npm/adapter/npm_cli_service_adapter_test.dart
  metrics/cli/test/test_utils/npm_service_mock.dart
Labels: size/L

#1271 feat: Update the SourceClient and DestinationClient interfaces
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/lib/integration/interface/destination/client/destination_client.dart
  metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
  metrics/ci_integrations/test/integration/ci/test_utils/stub/destination_client_stub.dart
  metrics/ci_integrations/test/integration/ci/test_utils/stub/source_client_stub.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/L

#1278 fix: Remove validator stub classes
  metrics/ci_integrations/lib/integration/stub/base/config/validation_delegate/validation_delegate_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator/validator_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/config_validator_factory_stub.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator/validator_stub_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator_factory/config_validator_factory_stub_test.dart
Labels: size/L

#1273 feat: Implement GitService
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/cli/git/git_command.dart
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/common/model/services.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/factory/deployer_factory.dart
  metrics/cli/lib/doctor/doctor.dart
  metrics/cli/lib/doctor/factory/doctor_factory.dart
  metrics/cli/lib/git/adapter/git_cli_service_adapter.dart
  metrics/cli/lib/git/service/git_service.dart
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/services_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deployer_factory_test.dart
  metrics/cli/test/doctor/doctor_test.dart
  metrics/cli/test/doctor/factory/doctor_factory_test.dart
  metrics/cli/test/git/adapter/git_cli_service_adapter_test.dart
  metrics/cli/test/test_utils/git_service_mock.dart
Labels: size/L

#1283 docs: Firebase aggregation analysis document
  metrics/firebase/docs/analysis/02_firebase_metrics_aggregation.md
Labels: size/L

#1280 feat: Implement `.fetchOneBuild` for the BuildkiteSourceClientAdapter
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
Labels: size/L

#1267 docs: [CI integrations] in-progress builds document
  metrics/ci_integrations/docs/06_builds_synchronization.md
  metrics/ci_integrations/docs/diagrams/add_coverage_data_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_builds_stage_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_single_build_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_algorithm_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_builds_stage_sequence_diagram.puml
  metrics/ci_integrations/docs/features/in_progress_builds/diagrams/destination_clients_class_diagram.puml
  metrics/ci_integrations/docs/features/in_progress_builds/diagrams/source_clients_class_diagram.puml
  metrics/ci_integrations/docs/features/in_progress_builds/diagrams/sync_command_class_diagram.puml
  metrics/ci_integrations/docs/features/in_progress_builds/in_progress_builds_introduction.md
Labels: size/XL

#1286 feat: Extend the JenkinsClient to include the `fetchBuildByNumber` method
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/firestore/firestore_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
  metrics/ci_integrations/test/test_utils/matchers.dart
Labels: size/L

#1290 feat: Implement `SyncStage`, `BuildsSyncStage`
  metrics/ci_integrations/lib/integration/ci/sync_stage/builds/builds_sync_stage.dart
  metrics/ci_integrations/lib/integration/ci/sync_stage/sync_stage.dart
  metrics/ci_integrations/test/integration/ci/sync_stage/builds/builds_sync_stage_test.dart
Labels: size/L

#1284 feat: Update FirestoreDestinationClientAdapter to match the updated interface
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
Labels: size/XL

#1298 feat: Implement `.fetchOneBuild` in the JenkinsSourceClientAdapter
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/L

#1288 feat: Implement `.fetchOneBuild()` in the GithubActionsSourceClientAdapter
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
Labels: size/XL

#1294 feat: Implement FirebaseService
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/cli/firebase/firebase_command.dart
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/common/model/services.dart
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/factory/deployer_factory.dart
  metrics/cli/lib/doctor/doctor.dart
  metrics/cli/lib/doctor/factory/doctor_factory.dart
  metrics/cli/lib/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/firebase/cli/firebase_cli.dart
  metrics/cli/lib/firebase/service/firebase_service.dart
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/services_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deployer_factory_test.dart
  metrics/cli/test/doctor/doctor_test.dart
  metrics/cli/test/doctor/factory/doctor_factory_test.dart
  metrics/cli/test/firebase/adapter/firebase_cli_service_adapter_test.dart
  metrics/cli/test/flutter/adapter/flutter_cli_service_adapter_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/test_utils/firebase_service_mock.dart
Labels: size/XXL

#1299 feat: Implement `NewBuildsSyncStage`
  metrics/ci_integrations/lib/integration/ci/sync_stage/builds/new_builds_sync_stage.dart
  metrics/ci_integrations/test/integration/ci/sync_stage/builds/new_builds_sync_stage_test.dart
Labels: size/XL

#1305 fix: Fix matchers in NewBuildsSyncStage tests
  metrics/ci_integrations/test/integration/ci/sync_stage/builds/new_builds_sync_stage_test.dart
Labels: Snake 🐍, size/S

#1296 docs: Firebase builds aggregation design document
  metrics/firebase/docs/features/builds_aggregation/01_firestore_builds_aggregation_design.md
  metrics/firebase/docs/features/builds_aggregation/diagrams/firestore_create_builds_aggregation_sequence_diagram.puml
  metrics/firebase/docs/features/builds_aggregation/diagrams/firestore_update_builds_aggregation_sequence_diagram.puml
Labels: size/L

#1311 feat: Implement security rules for the “tasks” collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/tasks-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: size/L

#1310 feat: Implement security rules for the “build_days” collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/build-days-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: size/L

#1315 fix: Update BuildData deserialization
  metrics/ci_integrations/lib/data/deserializer/build_data_deserializer.dart
  metrics/ci_integrations/test/data/deserializer/build_data_deserializer_test.dart
  metrics/web/lib/dashboard/data/deserializer/build_data_deserializer.dart
  metrics/web/test/dashboard/data/deserializer/build_data_deserializer_test.dart
Labels: Snake 🐍, size/S

#1303 feat: `FirestoreDestinationClientAdapter` error handling
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
Labels: size/L

#1304 feat: Implement SyncStagesFactory
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/integration/ci/sync_stage/builds/in_progress_builds_sync_stage.dart
  metrics/ci_integrations/lib/integration/ci/sync_stage/builds/new_builds_sync_stage.dart
  metrics/ci_integrations/lib/integration/ci/sync_stage/factory/sync_stages_factory.dart
  metrics/ci_integrations/test/integration/ci/ci_integration_test.dart
  metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
  metrics/ci_integrations/test/integration/ci/sync_stage/factory/sync_stages_factory_test.dart
Labels: size/XL

#1307 docs: Metrics Web Application builds aggregation design document
  metrics/web/docs/features/builds_aggregation/01_builds_aggregation_design.md
  metrics/web/docs/features/builds_aggregation/diagrams/build_days_data_layer_class_diagram.puml
  metrics/web/docs/features/builds_aggregation/diagrams/build_days_domain_layer_class_diagram.puml
  metrics/web/docs/features/builds_aggregation/diagrams/build_days_presentation_layer_class_diagram.puml
  metrics/web/docs/features/builds_aggregation/diagrams/build_days_sequence_diagram.puml
Labels: size/L

#1321 fix: [Metrics CLI] Improve login methods
  metrics/cli/lib/firebase/cli/firebase_cli.dart
  metrics/cli/lib/gcloud/cli/gcloud_cli.dart
Labels: Snake 🐍, size/XS

#1314 feat: Implement SentryService
  docs/16_dependencies_licenses.md
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/sentry/cli/sentry_cli.dart
  metrics/cli/lib/sentry/model/sentry_project.dart
  metrics/cli/lib/sentry/model/sentry_release.dart
  metrics/cli/lib/sentry/model/source_map.dart
  metrics/cli/lib/sentry/service/sentry_service.dart
  metrics/cli/lib/sentry/strings/sentry_strings.dart
  metrics/cli/pubspec.yaml
  metrics/cli/test/sentry/adapter/sentry_cli_service_adapter_test.dart
  metrics/cli/test/sentry/cli/sentry_cli_test.dart
  metrics/cli/test/sentry/model/sentry_project_test.dart
  metrics/cli/test/sentry/model/sentry_release_test.dart
  metrics/cli/test/sentry/model/source_map_test.dart
  metrics/cli/test/sentry/strings/sentry_strings_test.dart
  metrics/cli/test/test_utils/firebase_service_mock.dart
Labels: size/XL

#1317 feat: Add manual steps to the FirebaseCliServiceAdapter
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/common/model/metrics_config.dart
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/firebase/service/firebase_service.dart
  metrics/cli/lib/firebase/strings/firebase_strings.dart
  metrics/cli/test/common/model/metrics_config_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/firebase/adapter/firebase_cli_service_adapter_test.dart
Labels: size/XL

#1316 feat: Implement `InProgressBuildsSyncStage`
  metrics/ci_integrations/lib/integration/ci/sync_stage/builds/in_progress_builds_sync_stage.dart
  metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
Labels: size/XL

#1329 feat: Add accept terms method to the GCloudService
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/service/gcloud_service.dart
  metrics/cli/lib/gcloud/strings/gcloud_strings.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
Labels: size/L

#1326 feat: Update JenkinsSourceClientAdapter in-progress builds mapping
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/L

#1325 feat: Update BuildkiteSourceClientAdapter in-progress builds mapping
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/util/url/url_utils.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart
  metrics/ci_integrations/test/util/url/url_utils_test.dart
Labels: size/L

#1327 feat: Update GithubActionsSourceClientAdapter in-progress builds mapping
  metrics/ci_integrations/docs/features/in_progress_builds/in_progress_builds_introduction.md
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_test_data_generator.dart
Labels: size/L

#1338 feat: Builds aggregation - Domain Layer
  metrics/web/lib/common/domain/entities/build_day.dart
  metrics/web/lib/common/domain/repositories/build_day_repository.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_day_project_metrics.dart
  metrics/web/lib/dashboard/domain/entities/metrics/build_performance.dart
  metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
  metrics/web/lib/dashboard/domain/entities/metrics/performance_metric.dart
  metrics/web/lib/dashboard/domain/usecases/receive_build_day_project_metrics_updates.dart
  metrics/web/test/common/domain/entities/build_day_test.dart
  metrics/web/test/dashboard/domain/entities/metrics/build_day_project_metrics_test.dart
  metrics/web/test/dashboard/domain/entities/metrics/build_performance_test.dart
  metrics/web/test/dashboard/domain/entities/metrics/performance_metric_test.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_day_project_metrics_updates_test.dart
Labels: size/XL

#1328 feat: Integrate SentryService to the Metrics CLI
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/common/model/services.dart
  metrics/cli/lib/common/model/web_metrics_config.dart
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/factory/deployer_factory.dart
  metrics/cli/lib/deploy/strings/deploy_strings.dart
  metrics/cli/lib/doctor/doctor.dart
  metrics/cli/lib/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/sentry/model/sentry_config.dart
  metrics/cli/pubspec.yaml
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/metrics_config_test.dart
  metrics/cli/test/common/model/services_test.dart
  metrics/cli/test/common/model/web_metrics_config_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deployer_factory_test.dart
  metrics/cli/test/doctor/doctor_test.dart
  metrics/cli/test/doctor/factory/doctor_factory_test.dart
  metrics/cli/test/sentry/adapter/sentry_cli_service_adapter_test.dart
  metrics/cli/test/sentry/model/sentry_config_test.dart
  metrics/cli/test/test_utils/sentry_service_mock.dart
  metrics/core/lib/metrics_core.dart
  metrics/core/lib/src/domain/entities/metrics_config.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/platform/stub/metrics_config/metrics_config_factory.dart
  metrics/web/lib/platform/web/metrics_config/metrics_config_factory.dart
  metrics/web/lib/platform/web/metrics_config/web_metrics_config.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/test_utils/metrics_config_stub.dart
Labels: size/XL

#1345 chore: reword decision section to simplify reading
  metrics/firebase/docs/analysis/02_firebase_metrics_aggregation.md
Labels: Snake 🐍, size/XS

#1334 feat: Introduce new in-progress assets
  metrics/web/lib/base/presentation/widgets/rive_animation.dart
  metrics/web/lib/common/presentation/asset/strategy/value_based_asset_strategy.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/project_build_status/attention_level/project_build_status_attention_level.dart
  metrics/web/lib/common/presentation/value_image/strategy/value_based_image_asset_strategy.dart
  metrics/web/lib/common/presentation/value_image/widgets/value_network_image.dart
  metrics/web/lib/common/presentation/widgets/build_status_view.dart
  metrics/web/lib/common/presentation/widgets/metrics_theme_image.dart
  metrics/web/lib/common/presentation/widgets/theme_mode_builder.dart
  metrics/web/lib/common/presentation/widgets/timer_notifier_builder.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_popup_card.dart
  metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_popup_asset_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_asset_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/test/common/presentation/metrics_theme/model/project_build_status/attention_level/project_build_status_attention_level_test.dart
  metrics/web/test/common/presentation/value_image/widgets/value_network_image_test.dart
  metrics/web/test/common/presentation/widgets/build_status_view_test.dart
  metrics/web/test/common/presentation/widgets/metrics_theme_image_test.dart
  metrics/web/test/common/presentation/widgets/theme_mode_builder_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_popup_asset_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_asset_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
  metrics/web/test/test_utils/finder_util.dart
  metrics/web/web/animation/in_progress_popup_build_status.riv
  metrics/web/web/animation/in_progress_project_build_status_dark.riv
  metrics/web/web/animation/in_progress_project_build_status_light.riv
Labels: size/XXL

#1342 feat: Builds Aggregations - Implement Data Layer
  metrics/web/lib/common/data/model/build_day_data.dart
  metrics/web/lib/common/data/repositories/firestore_build_day_repository.dart
  metrics/web/test/common/data/model/build_day_data_test.dart
Labels: size/L

#1352 fix: Fix error handling in main.dart
  metrics/cli/bin/main.dart
Labels: Snake 🐍, size/XS

#1349 docs: Update concept map to include all Metrics components
  concept_map.puml
  readme.md
Labels: size/M
