Repository Flank/flank-dashboard, pull requests merged in 2021-06, with the labels that each got.

#1441 docs: Feature design template update
  docs/19_feature_design_template.md
Labels: Snake 🐍, size/M

#1443 docs: Update Deep Links analysis document
  metrics/web/docs/analysis/deep_links/01_deep_links_analysis.md
  metrics/web/docs/analysis/deep_links/diagrams/applying_deep_links_sequence_diagram.puml
  metrics/web/docs/analysis/deep_links/diagrams/saving_deep_links_sequence_diagram.puml
  metrics/web/docs/features/deep_links/01_deep_linking.md
  metrics/web/docs/features/deep_links/diagrams/custom_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/deep_links_integration_component_diagram.puml
Labels: Snake 🐍, size/XL

#1447 docs: Deep Links Design (`Approach`, `Parsing Deep Links` sections)
  metrics/web/docs/features/deep_links/01_deep_linking.md
  metrics/web/docs/features/deep_links/diagrams/custom_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/navigation_notifier_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/parsing_deep_links_class_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/route_parameters_approach_component_diagram.puml
Labels: size/L

#1444 docs: Metrics storybook analysis document
  metrics/web/docs/features/storybook/01_metrics_storybook_design.md
  metrics/web/docs/features/storybook/diagrams/metrics_storybook_web_relation_diagram.puml
Labels: size/L

#1455 docs: Improve the deep links design document
  metrics/web/docs/features/deep_links/01_deep_linking.md
  metrics/web/docs/features/deep_links/diagrams/parsing_deep_links_class_diagram.puml
Labels: Snake 🐍, size/S

#1442 docs: Analyze Metrics CLI update/redeploy feature
  metrics/cli/docs/features/diagrams/update_feature_integration_component_diagram.puml
  metrics/cli/docs/features/update/06_update_feature.md
Labels: size/L

#1456 fix: Improve the Metrics Storybook analysis document
  metrics/web/docs/features/storybook/01_metrics_storybook_design.md
  metrics/web/docs/features/storybook/diagrams/metrics_storybook_web_relation_diagram.puml
Labels: Snake 🐍, size/S

#1451 feat: Update the `RouteConfiguration` class to include the `parameters` field
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/common/presentation/navigation/metrics_route_information_parser.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_location_converter.dart
  metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_location_converter_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_test.dart
Labels: size/L

#1458 feat: Update the `RouteConfiguration` class to include the named constructors
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/drawer/widget/metrics_drawer.dart
  metrics/web/lib/common/presentation/navigation/constants/default_routes.dart
  metrics/web/lib/common/presentation/navigation/constants/metrics_routes.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/test/analytics/domain/entities/page_name_test.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/drawer/widget/metrics_drawer_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_route_test.dart
  metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_location_converter_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/test_utils/route_configuration_mock.dart
  metrics/web/test/test_utils/route_configuration_stub.dart
Labels: size/XL

#1449 docs: Deep Links design document - application section
  metrics/web/docs/features/deep_links/01_deep_linking.md
  metrics/web/docs/features/deep_links/diagrams/applying_deep_links_sequence_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/custom_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/deep_links_and_authorization_sequence_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/deep_links_class_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/deep_links_integration_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/navigation_notifier_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/page_parameters_model_class_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/parsing_deep_links_class_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/route_parameters_approach_component_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/updating_deep_links_sequence_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/updating_page_parameters_sequence_diagram.puml
Labels: Snake 🐍, size/XL

#1460 docs: Fix diagram in "Doctor Output Improvements"
  metrics/cli/docs/features/doctor_output_improvements/06_doctor_output_improvements.md
Labels: Snake 🐍, size/XS

#1467 docs: Improve diagrams in "Deep Linking" design doc
  metrics/web/docs/features/deep_links/diagrams/applying_deep_links_sequence_diagram.puml
  metrics/web/docs/features/deep_links/diagrams/updating_page_parameters_sequence_diagram.puml
Labels: Snake 🐍, size/M

#1459 docs: Design update/redeploy feature
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/metrics_cli_runner_class_diagram.puml
  metrics/cli/docs/features/update/06_update_feature.md
  metrics/cli/docs/features/update/config/configuration_template.yaml
  metrics/cli/docs/features/update/diagrams/config_yaml_parser_class_diagram.puml
  metrics/cli/docs/features/update/diagrams/update_command_components_diagram.puml
  metrics/cli/docs/features/update/diagrams/update_command_sequence_diagram.puml
  metrics/cli/docs/features/update/diagrams/update_config_class_diagram.puml
  metrics/cli/docs/features/update/diagrams/update_feature_integration_component_diagram.puml
  metrics/cli/docs/features/update/diagrams/updater_class_diagram.puml
Labels: size/XL

#1469 docs: add privacy and security sections to the feature template
  docs/19_feature_design_template.md
Labels: Snake 🐍, size/S

#1468 feat: Update cli services to add auth token parameters
  metrics/cli/docs/features/update/diagrams/updater_class_diagram.puml
  metrics/cli/lib/cli/deployer/deployer.dart
  metrics/cli/lib/cli/deployer/factory/deployer_factory.dart
  metrics/cli/lib/cli/deployer/model/factory/deploy_paths_factory.dart
  metrics/cli/lib/common/model/factory/paths_factory.dart
  metrics/cli/lib/common/model/paths.dart
  metrics/cli/lib/common/model/sentry_web_config.dart
  metrics/cli/lib/common/model/web_metrics_config.dart
  metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/services/firebase/cli/firebase_cli.dart
  metrics/cli/lib/services/firebase/firebase_service.dart
  metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/services/sentry/cli/sentry_cli.dart
  metrics/cli/lib/services/sentry/sentry_service.dart
  metrics/cli/test/cli/deployer/deployer_test.dart
  metrics/cli/test/cli/deployer/model/factory/deploy_paths_factory_test.dart
  metrics/cli/test/common/model/factory/paths_factory_test.dart
  metrics/cli/test/common/model/paths_test.dart
  metrics/cli/test/common/model/sentry_web_config_test.dart
  metrics/cli/test/common/model/web_metrics_config_test.dart
  metrics/cli/test/prompter/prompter_test.dart
  metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
  metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart
Labels: size/XL
