Repository Flank/flank-dashboard, pull requests merged in 2021-07, with the labels that each got.

#1476 feat: Update recommended_versions.yaml
  metrics/cli/dependencies.yaml
Labels: size/M

#1473 feat: Implement DashboardPageParametersModel
  metrics/web/lib/common/presentation/navigation/models/page_parameters_model.dart
  metrics/web/lib/dashboard/presentation/models/dashboard_page_parameters_model.dart
  metrics/web/test/dashboard/presentation/models/dashboard_page_parameters_model_test.dart
Labels: size/L

#1479 feat: Implement Page Parameters Factory
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/models/factory/page_parameters_factory.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/models/factory/page_parameters_factory_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/test_utils/route_name_mock.dart
Labels: size/L

#1477 feat: Add an ability to set the auth token for the whole CLI class
  metrics/cli/lib/services/common/auth_service.dart
  metrics/cli/lib/services/common/cli/auth_cli.dart
  metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/services/firebase/cli/firebase_cli.dart
  metrics/cli/lib/services/firebase/firebase_service.dart
  metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/services/sentry/cli/sentry_cli.dart
  metrics/cli/lib/services/sentry/sentry_service.dart
  metrics/cli/test/common/model/paths/paths_test.dart
  metrics/cli/test/common/strings/common_strings_test.dart
  metrics/cli/test/services/common/auth_cli_test.dart
  metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
  metrics/cli/test/services/firebase/strings/firebase_strings_test.dart
  metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/services/gcloud/strings/gcloud_strings_test.dart
  metrics/cli/test/services/git/adapter/git_cli_service_adapter_test.dart
  metrics/cli/test/services/npm/adapter/npm_cli_service_adapter_test.dart
  metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart
  metrics/cli/test/services/sentry/strings/sentry_strings_test.dart
Labels: size/XL

#1480 docs: Metrics CLI versioning support analysis
  metrics/cli/docs/features/supported_storage_version/01_supported_storage_version.md
  metrics/cli/docs/features/supported_storage_version/diagrams/storage_version_components_diagram.puml
Labels: size/L

#1470 docs: Doctor output improvements design document
  metrics/cli/docs/features/doctor_output_improvements/01_doctor_output_improvements.md
  metrics/cli/docs/features/doctor_output_improvements/diagrams/ci_integrations_validator_class_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/ci_integrations_validator_sequence_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/config_validation_conclusion_class_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/cool_integration_source_validation_target_class_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/doctor_output_feature_component_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/doctor_output_improvements_class_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/doctor_output_improvements_sequence_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/metrics_cli_class_diagram.puml
  metrics/cli/docs/features/doctor_output_improvements/diagrams/validation_class_diagram.puml
Labels: size/XL

#1484 docs: Public dashboard analysis
  metrics/web/docs/features/public_dashboard/01_public_dashboard.md
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_components.puml
Labels: size/L

#1486 feat: Metrics page updates
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page.dart
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_factory.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_test.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
Labels: size/L

#1511 feat: Create stubs for CI Integration's validation
  metrics/ci_integrations/lib/integration/stub/base/config/validation_delegate/validation_delegate_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator/config_validator_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/config_validator_factory_stub.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator/config_validator_stub_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator_factory/config_validator_factory_stub_test.dart
Labels: size/L

#1531 feat: Implement the Dependency model
  metrics/cli/lib/util/dependencies/dependency.dart
  metrics/cli/test/util/dependencies/dependency_test.dart
Labels: size/M

#1532 feat: Update ValidateCommand to use validation from Metrics Core
  metrics/ci_integrations/lib/cli/command/validate_command.dart
  metrics/ci_integrations/lib/destination/firestore/config/validator/firestore_destination_validator.dart
  metrics/ci_integrations/lib/destination/firestore/config/validator_factory/firestore_destination_validator_factory.dart
  metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validator/config_validator.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator/validator_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/validator_factory_stub.dart
  metrics/ci_integrations/lib/integration/validation/model/config_field_validation_conclusion.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator_factory/buildkite_source_validator_factory.dart
  metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator_factory/github_actions_source_validator_factory.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/lib/source/jenkins/config/validator/jenkins_source_validator.dart
  metrics/ci_integrations/lib/source/jenkins/config/validator_factory/jenkins_source_validator_factory.dart
  metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
  metrics/ci_integrations/test/cli/command/validate_command_test.dart
  metrics/ci_integrations/test/destination/firestore/party/firestore_destination_party_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator/validator_stub_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator_factory/validator_factory_stub_test.dart
  metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart
  metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart
  metrics/ci_integrations/test/source/jenkins/party/jenkins_source_party_test.dart
Labels: size/L

#1509 feat: Add a handlePageParametersUpdates method to the NavigationNotifier
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
Labels: size/L

#1533 feat: Implement Dependencies and DependenciesFactory
  metrics/cli/lib/util/dependencies/dependencies.dart
  metrics/cli/lib/util/dependencies/factory/dependencies_factory.dart
  metrics/cli/test/util/dependencies/dependencies_test.dart
  metrics/cli/test/util/dependencies/factory/dependencies_factory_test.dart
Labels: size/L

#1536 feat: Implement ServiceName and ServiceNameMapper
  metrics/cli/lib/services/common/service/model/mapper/service_name_mapper.dart
  metrics/cli/lib/services/common/service/model/service_name.dart
  metrics/cli/test/services/common/cli/auth_cli_test.dart
  metrics/cli/test/services/common/service/model/mapper/service_name_mapper_test.dart
Labels: size/L

#1539 fix: Fix ValidationResultBuilder
  metrics/core/lib/src/util/validation/validation_result_builder.dart
  metrics/core/test/util/validation/validation_result_builder_test.dart
Labels: Snake 🐍, size/M

#1537 feat: Update services to include ServiceName
  metrics/cli/lib/services/common/info_service.dart
  metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/services/firebase/firebase_service.dart
  metrics/cli/lib/services/flutter/adapter/flutter_cli_service_adapter.dart
  metrics/cli/lib/services/flutter/flutter_service.dart
  metrics/cli/lib/services/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/services/gcloud/gcloud_service.dart
  metrics/cli/lib/services/git/adapter/git_cli_service_adapter.dart
  metrics/cli/lib/services/git/git_service.dart
  metrics/cli/lib/services/npm/adapter/npm_cli_service_adapter.dart
  metrics/cli/lib/services/npm/npm_service.dart
  metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/services/sentry/sentry_service.dart
Labels: size/M

#1538 feat: Update services' version checking
  metrics/cli/lib/cli/doctor/doctor.dart
  metrics/cli/lib/services/common/info_service.dart
  metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
  metrics/cli/lib/services/firebase/cli/firebase_cli.dart
  metrics/cli/lib/services/flutter/adapter/flutter_cli_service_adapter.dart
  metrics/cli/lib/services/flutter/cli/flutter_cli.dart
  metrics/cli/lib/services/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/services/gcloud/cli/gcloud_cli.dart
  metrics/cli/lib/services/git/adapter/git_cli_service_adapter.dart
  metrics/cli/lib/services/git/cli/git_cli.dart
  metrics/cli/lib/services/npm/adapter/npm_cli_service_adapter.dart
  metrics/cli/lib/services/npm/cli/npm_cli.dart
  metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
  metrics/cli/lib/services/sentry/cli/sentry_cli.dart
  metrics/cli/test/cli/doctor/doctor_test.dart
  metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
  metrics/cli/test/services/flutter/adapter/flutter_cli_service_adapter_test.dart
  metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/services/git/adapter/git_cli_service_adapter_test.dart
  metrics/cli/test/services/npm/adapter/npm_cli_service_adapter_test.dart
  metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart
Labels: size/L
