Repository Flank/flank-dashboard, pull requests merged in 2021-09, with the labels that each got.

#1585 feat: Integrate the AuthState enum to the NavigationNotifier
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
Labels: size/S

#1588 feat: Update firestore security rules of project collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/projects-test.js
Labels: size/L

#1592 fix: Fix merged firebase rules tests
  metrics/firebase/test/firestore/rules/project-groups-test.js
  metrics/firebase/test/firestore/rules/projects-test.js
Labels: size/S

#1587 feat: Add the isInitialized getter to the AuthNotifier
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/test/auth/presentation/state/auth_notifier_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/M

#1590 feat: Update firestore security rules of user profiles collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/user-profiles-test.js
Labels: size/XL

#1589 feat: Update firestore security rules of builds collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/builds-test.js
Labels: size/L

#1591 feat: Update build days collection security rules
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/build-days-test.js
Labels: size/L

#1595 refactor: Refactor firestore.rules
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/allowed-email-domains-test.js
  metrics/firebase/test/firestore/rules/feature-config-test.js
  metrics/firebase/test/firestore/rules/tasks-test.js
Labels: size/M

#1586 feat: Change the MetricsUserMenu UI depending on the user authentication state
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/auth/presentation/view_models/user_profile_view_model.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/test/auth/presentation/view_models/user_profile_view_model_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/L

#1593 feat: Add the navigation logic for the anonymous user
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test_driver/app_test.dart
Labels: size/L

#1596 fix: Fix deep links with anonymous user login
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/test_driver/app_test.dart
Labels: size/S

#1598 feat: Add manufacturer banner
  metrics/web/lib/common/presentation/manufacturer_advertisement_container/widget/manufacturer_advertisement_container.dart
  metrics/web/lib/common/presentation/manufacturer_banner/theme/theme_data/manufacturer_banner_theme_data.dart
  metrics/web/lib/common/presentation/manufacturer_banner/widget/manufacturer_banner.dart
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
  metrics/web/lib/common/presentation/strings/common_strings.dart
  metrics/web/test/common/presentation/manufacturer_advertisement_container/widget/manufacturer_advertisement_container_test.dart
  metrics/web/test/common/presentation/manufacturer_banner/widget/manufacturer_banner_test.dart
  metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/web/icons/solid_logo.svg
Labels: size/XL
