Repository Flank/flank-dashboard, pull requests merged in 2021-02, with the labels that each got.

#1031 feat: Implement Buildkite Validation Models
  metrics/ci_integrations/lib/client/buildkite/mappers/buildkite_token_scope_mapper.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_organization.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_pipeline.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_token.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_token_scope.dart
  metrics/ci_integrations/test/client/buildkite/mappers/buildkite_build_state_mapper_test.dart
  metrics/ci_integrations/test/client/buildkite/mappers/buildkite_token_scope_mapper_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_organization_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_pipeline_test.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_token_test.dart
Labels: size/XXL

#1035 build: Upgrade Firebase SDK version
  docs/09_firebase_deployment.md
  docs/19_security_audit_document.md
  metrics/web/web/index.html
Labels: size/S

#1045 feat: Change Stability metrics calculation
  docs/05_project_metrics.md
  docs/06_metrics_dashboard.md
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
Labels: size/M

#1047 docs: Update Ci integrations config validator doc with `validate` command
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml
Labels: size/L

#1050 feat: Build Result metric changes
  docs/05_project_metrics.md
  docs/06_metrics_dashboard.md
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
Labels: size/L

#1056 fix: Improve BuildResultBar hitTestBehaviour
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
Labels: Snake 🐍, size/M

#1048 feat: Project groups dropdown animation
  metrics/web/lib/common/presentation/constants/duration_constants.dart
  metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart
Labels: size/L

#1044 feat: jenkins pipelines added
  .jenkins/jobs/ci_integrations.groovy
  .jenkins/jobs/coverage_converter.groovy
  .jenkins/jobs/monorepo.groovy
  .jenkins/jobs/sync.groovy
  .jenkins/jobs/web.groovy
  .jenkins/pipelines/ci_integrations.groovy
  .jenkins/pipelines/coverage_converter.groovy
  .jenkins/pipelines/monorepo.groovy
  .jenkins/pipelines/sync.groovy
  .jenkins/pipelines/web.groovy
  .metrics/jenkins/ci_integrations_config.yml
  .metrics/jenkins/config_template.yml
  .metrics/jenkins/metrics_web_config.yml
Labels: size/L

#1053 feat: Extend Buildkite client to include validation-required methods
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
Labels: size/L

#1034 feat: GitHub Actions fetch coverage
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
Labels: size/XL

#1059 fix: Add missing fields to the Github Actions config template
  metrics/ci_integrations/docs/source/github_actions/config/configuration_template.yaml
Labels: Snake 🐍, size/M

#1067 refactor: Move Debug Menu strings to `presentation` layer
  metrics/web/lib/debug_menu/presentation/pages/debug_menu_page.dart
  metrics/web/lib/debug_menu/presentation/state/debug_menu_notifier.dart
  metrics/web/lib/debug_menu/presentation/strings/debug_menu_strings.dart
  metrics/web/lib/debug_menu/presentation/widgets/debug_menu_fps_monitor_toggle.dart
  metrics/web/lib/debug_menu/presentation/widgets/debug_menu_renderer_display.dart
  metrics/web/test/debug_menu/presentation/pages/debug_menu_page_test.dart
  metrics/web/test/debug_menu/presentation/state/debug_menu_notifier_test.dart
  metrics/web/test/debug_menu/presentation/widgets/debug_menu_fps_monitor_toggle_test.dart
  metrics/web/test/debug_menu/presentation/widgets/debug_menu_renderer_display_test.dart
  metrics/web/test/test_utils/debug_menu_notifier_stub.dart
Labels: Snake 🐍

#1057 feat: Implement Buildkite source validation delegate
  metrics/ci_integrations/lib/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/buildkite/strings/buildkite_strings.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/buildkite/test_utils/buildkite_client_mock.dart
Labels: size/XL

#1068 docs: Store database metadata
  metrics/docs/01_storing_database_metadata.md
Labels: size/L

#1055 feat: Jenkins fetch coverage
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/client/jenkins/builder/jenkins_url_builder.dart
  metrics/ci_integrations/lib/client/jenkins/constants/jenkins_constants.dart
  metrics/ci_integrations/lib/client/jenkins/deserializer/jenkins_build_deserializer.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_build.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_building_job.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/lib/util/url/url_utils.dart
  metrics/ci_integrations/test/client/jenkins/builder/jenkins_url_builder_test.dart
  metrics/ci_integrations/test/client/jenkins/deserializer/jenkins_build_deserializer_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_build_test.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_building_job_test.dart
  metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
  metrics/ci_integrations/test/client/jenkins/test_utils/test_data/jenkins_build_test_data.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
  metrics/ci_integrations/test/util/url/url_utils_test.dart
Labels: size/XXL

#1074 docs: firebase deployment fix suggestions
  docs/09_firebase_deployment.md
Labels: size/S

#1071 feat: Publish sha for linux binaries
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
Labels: size/M

#1065 docs: Update CI Integrations Config Validator design
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_destination_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_interfaces_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml
Labels: size/XL

#1070 feat: replace pipelines with dummy ones
  .buildkite/compose-files/docker-compose.yml
  .buildkite/pipelines/ci_integrations_pipeline.yml
  .buildkite/pipelines/coverage_converter_pipeline.yml
  .buildkite/pipelines/dummy_pipeline.yml
  .buildkite/pipelines/metrics_web_pipeline.yml
  .buildkite/pipelines/monorepo_pipeline.yml
  .buildkite/pipelines/sync_pipeline.yml
  .jenkins/jobs/ci_integrations.groovy
  .jenkins/jobs/coverage_converter.groovy
  .jenkins/jobs/dummy.groovy
  .jenkins/jobs/web.groovy
  .jenkins/pipelines/ci_integrations.groovy
  .jenkins/pipelines/coverage_converter.groovy
  .jenkins/pipelines/dummy.groovy
  .jenkins/pipelines/monorepo.groovy
  .jenkins/pipelines/sync.groovy
  .jenkins/pipelines/web.groovy
  scripts/random_sleep/random_sleep.sh
Labels: size/XL

#1073 feat: CI integrations sync - check project exists
  metrics/ci_integrations/lib/destination/error/destination_error.dart
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/test/destination/error/destination_error_test.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
Labels: size/L

#1085 feat: Implement a new bar chart design
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
  metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
Labels: size/L

#1081 docs: Metrics Web supported database version design
  metrics/docs/01_storing_database_metadata.md
  metrics/web/docs/features/supported_database_version/01_supported_database_version.md
  metrics/web/docs/features/supported_database_version/diagrams/database_finished_updating_sequence_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_data_class_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_domain_class_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_presentation_class_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_sequence_diagram.puml
Labels: size/L

#1087 fix: fixed prod sync pipeline
  .buildkite/pipelines/prod_sync_pipeline.yml
Labels: size/S

#1091 feat: Add a date range to the bar chart
  metrics/web/lib/common/presentation/metrics_theme/model/build_result_bar_graph/theme_data/build_result_bar_graph_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/test/common/presentation/metrics_theme/model/build_result_bar_graph/theme_data/build_result_bar_graph_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
Labels: size/L

#1082 feat: migrate jenkins to k8s
  .jenkins/jobs/dummy.groovy
  .jenkins/pipelines/dummy.groovy
  .jenkins/pipelines/sync.groovy
  .jenkins/pod_templates/ubuntu.yaml
Labels: size/M

#1094 refactor: Metrics CLI doc: Improve naming. Fix non-ascii symbols
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/diagrams/deploy_command_activity_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_activity_diagram.puml
  metrics/cli/docs/diagrams/metrics_cli_runner_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
Labels: Snake 🐍, size/M

#1099 docs: Metrics CLI design improvements
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/diagrams/cli_interfaces_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_activity_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_activity_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/metrics_cli_runner_class_diagram.puml
  metrics/cli/docs/diagrams/prompt_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
Labels: Snake 🐍, size/L

#1100 feat: Metrics Colors Palette
  metrics/web/lib/base/presentation/widgets/circle_graph_indicator.dart
  metrics/web/lib/common/presentation/graph_indicator/theme/style/graph_indicator_style.dart
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/metrics_colors.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_field_config.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_color/metrics_color.dart
  metrics/web/lib/common/presentation/metrics_theme/widgets/metrics_theme_builder.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_color/metrics_color_test.dart
  metrics/web/test/common/presentation/metrics_theme/widget/metrics_theme_test.dart
Labels: size/XXL

#1108 feat: Add sha256 for macOS builds
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
Labels: size/M

#1101 docs: Analyze sign tools for Metrics binaries
  metrics/docs/02_sign_and_notarize_metrics_binaries.md
Labels: size/L

#1103 docs: Update Config Validator design
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_destination_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_interfaces_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/config_validator_base_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/config_validator_destination_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/config_validator_sequence_diagram.puml
Labels: size/XL

#1111 feat: Validation Result interfaces and base classes
  metrics/ci_integrations/docs/diagrams/config_validator_base_class_diagram.puml
  metrics/ci_integrations/lib/integration/interface/base/config/model/config_field.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validator/config_validator.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validator_factory/config_validator_factory.dart
  metrics/ci_integrations/lib/integration/validation/model/field_validation_conclusion.dart
  metrics/ci_integrations/lib/integration/validation/model/field_validation_result.dart
  metrics/ci_integrations/lib/integration/validation/model/mappers/field_validation_conclusion_mapper.dart
  metrics/ci_integrations/lib/integration/validation/model/validation_result.dart
  metrics/ci_integrations/lib/integration/validation/model/validation_result_builder.dart
  metrics/ci_integrations/test/integration/interface/base/config/model/config_field_test.dart
  metrics/ci_integrations/test/integration/interface/base/config/validator/config_validator_test.dart
  metrics/ci_integrations/test/integration/validation/model/field_validation_result_test.dart
  metrics/ci_integrations/test/integration/validation/model/mappers/field_validation_conclusion_mapper_test.dart
  metrics/ci_integrations/test/integration/validation/model/validation_result_builder_test.dart
  metrics/ci_integrations/test/integration/validation/model/validation_result_test.dart
  metrics/ci_integrations/test/test_utils/config_field_stub.dart
  metrics/ci_integrations/test/test_utils/matcher_util.dart
Labels: size/XL

#1112 feat: Add ignore option to the Links Checker
  .github/workflows/metrics_actions.yml
  scripts/links_checker/lib/arguments/models/links_checker_arguments.dart
  scripts/links_checker/lib/arguments/parser/links_checker_arguments_parser.dart
  scripts/links_checker/lib/command/links_checker_command.dart
  scripts/links_checker/test/arguments/models/links_checker_arguments_tests.dart
  scripts/links_checker/test/arguments/parser/links_checker_arguments_parser_test.dart
  scripts/links_checker/test/command/links_checker_command_test.dart
Labels: size/L

#1109 feat: Enable contributor CLA
  .github/workflows/cla.yml
Labels: size/S

#1117 fix: Add CLA document
  .github/workflows/cla.yml
  cla.md
Labels: Snake 🐍, size/S

#1114 feat: Implement BuildkiteSourceValidator, BuildkiteSourceValidatorFactory
  metrics/ci_integrations/lib/integration/validation/model/field_validation_result.dart
  metrics/ci_integrations/lib/integration/validation/model/validation_result_builder.dart
  metrics/ci_integrations/lib/source/buildkite/config/model/buildkite_source_config_field.dart
  metrics/ci_integrations/lib/source/buildkite/config/vaildator_factory/buildkite_source_validator_factory.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
  metrics/ci_integrations/lib/source/buildkite/strings/buildkite_strings.dart
  metrics/ci_integrations/test/integration/validation/model/field_validation_result_test.dart
  metrics/ci_integrations/test/integration/validation/model/validation_result_builder_test.dart
  metrics/ci_integrations/test/integration/validation/model/validation_result_test.dart
  metrics/ci_integrations/test/source/buildkite/config/model/buildkite_source_config_field_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator_factory/buildkite_source_validator_factory_test.dart
Labels: size/XL

#1115 docs: Investigate the way of enabling the Firebase Analytics
  metrics/cli/docs/02_enabling_firebase_analytics.md
Labels: size/M

#1113 feat: Implement a bar chart to match latest design
  metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
  metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
Labels: size/M

#1120 docs: Investigate the way of enabling the Firebase Authentication
  metrics/cli/docs/03_enablig_firebase_authentication.md
Labels: size/L

#1118 feat: Add an empty user-agent header for the API calls
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/constants/http_constants.dart
  metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
  metrics/ci_integrations/lib/source/buildkite/config/vaildator_factory/buildkite_source_validator_factory.dart
  metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
  metrics/ci_integrations/lib/source/jenkins/client_factory/jenkins_source_client_factory.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
Labels: size/L

#1123 feat: Implement Github Actions Validation Models
  metrics/ci_integrations/lib/client/github_actions/mappers/github_token_scope_mapper.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_actions_workflow.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_repository.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_token.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_token_scope.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_user.dart
  metrics/ci_integrations/test/client/github_actions/mappers/github_token_scope_mapper_test.dart
  metrics/ci_integrations/test/client/github_actions/models/github_actions_workflow_test.dart
  metrics/ci_integrations/test/client/github_actions/models/github_repository_test.dart
  metrics/ci_integrations/test/client/github_actions/models/github_token_test.dart
  metrics/ci_integrations/test/client/github_actions/models/github_user_test.dart
Labels: size/XL

#1124 docs: Investigate the way of managing Firestore data
  metrics/cli/docs/04_managing_firestore_data.md
  metrics/cli/docs/diagrams/services_class_diagram.puml
Labels: size/L

#1127 feat: Implement Jenkins models
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_instance_info.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_user.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_instance_info_test.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_user_test.dart
Labels: size/L

#1125 feat: Inject ConfigValidatorFactory to IntegrationParty interface
  metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
  metrics/ci_integrations/lib/integration/interface/base/party/integration_party.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validation_delegate/validation_delegate_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator/validator_stub.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/config_validator_factory_stub.dart
  metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/destination/firestore/party/firestore_destination_party_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validation_delegate/validation_delegate_stub_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator/validator_stub_test.dart
  metrics/ci_integrations/test/integration/stub/base/config/validator_factory/config_validator_factory_stub_test.dart
  metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart
  metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart
  metrics/ci_integrations/test/source/jenkins/party/jenkins_source_party_test.dart
  metrics/ci_integrations/test/test_utils/config_stub.dart
Labels: size/L

#1132 docs: Rename Analyze section to Analysis
  metrics/cli/docs/02_enabling_firebase_analytics.md
  metrics/cli/docs/03_enablig_firebase_authentication.md
  metrics/cli/docs/04_managing_firestore_data.md
  metrics/docs/02_sign_and_notarize_metrics_binaries.md
Labels: Snake 🐍, size/XS

#1136 chore: feature design template
  docs/20_feature_design_template.md
Labels: Snake 🐍, size/M

#1138 fix: Add missing closing punctuation to the template document.
  docs/00_template.md
Labels: Snake 🐍, size/XS
