Repository Flank/flank-dashboard, pull requests merged in 2021-05, with the labels that each got.

#1339 fix: Improve the temporary directory name
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/factory/deploy_paths_factory.dart
  metrics/cli/lib/deploy/factory/deployer_factory.dart
  metrics/cli/lib/deploy/model/deploy_paths.dart
  metrics/cli/lib/helper/file_helper.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deploy_paths_factory_test.dart
  metrics/cli/test/deploy/model/deploy_paths_test.dart
  metrics/cli/test/helper/file_helper_test.dart
Labels: size/L

#1353 feat: Add the user prompt to explain how to set up the Oauth 2.0 authorized JavaScript origins
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/service/gcloud_service.dart
  metrics/cli/lib/gcloud/strings/gcloud_strings.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/gcloud/strings/gcloud_strings_test.dart
Labels: size/L

#1340 feat: Implement onCreate Firestore Cloud Function trigger for build collection
  docs/16_dependencies_licenses.md
  metrics/core/lib/metrics_core.dart
  metrics/core/lib/src/util/date.dart
  metrics/firebase/firebase.json
  metrics/firebase/functions/.gitignore
  metrics/firebase/functions/analysis_options.yaml
  metrics/firebase/functions/build.yaml
  metrics/firebase/functions/index.js
  metrics/firebase/functions/lib/deserializers/build_data_deserializer.dart
  metrics/firebase/functions/lib/main.dart
  metrics/firebase/functions/lib/mappers/build_day_status_field_name_mapper.dart
  metrics/firebase/functions/lib/models/build_day_data.dart
  metrics/firebase/functions/lib/models/build_day_status_field.dart
  metrics/firebase/functions/lib/models/build_day_status_field_name.dart
  metrics/firebase/functions/lib/models/task_code.dart
  metrics/firebase/functions/lib/models/task_data.dart
  metrics/firebase/functions/package.json
  metrics/firebase/functions/pubspec.yaml
  metrics/firebase/functions/test/deserializers/build_data_deserializer_test.dart
  metrics/firebase/functions/test/main_test.dart
  metrics/firebase/functions/test/mappers/build_day_status_field_name_mapper_test.dart
  metrics/firebase/functions/test/models/build_day_data_test.dart
  metrics/firebase/functions/test/models/build_day_status_field_name_test.dart
  metrics/firebase/functions/test/models/build_day_status_field_test.dart
  metrics/firebase/functions/test/models/task_code_test.dart
  metrics/firebase/functions/test/models/task_data_test.dart
  metrics/firebase/functions/test/test_utils/test_data/build_test_data_generator.dart
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/widgets/date_range.dart
  metrics/web/test/dashboard/domain/usecases/receive_project_metrics_updates_test.dart
Labels: size/XXL

#1358 feat: Update Project Metrics Documentation
  design/black_theme/design.png
  design/light_theme/design.png
  docs/01_design_doc.md
  docs/05_project_metrics.md
  docs/06_code_coverage_artifact_import.md
  docs/06_metrics_dashboard.md
  docs/07_jenkins_testing_environment.md
  docs/08_firebase_deployment.md
  docs/09_dart_code_style.md
  docs/10_collaboration.md
  docs/11_ecosystem.md
  docs/12_state_management_investigation.md
  docs/13_firebase_deployment_cli.md
  docs/14_developer_configuration.md
  docs/15_dependencies_licenses.md
  docs/16_buildkite_ci_integration.md
  docs/17_github_actions_metrics_integration.md
  docs/18_security_audit_document.md
  docs/19_feature_design_template.md
  docs/images/build_results_bar.png
  docs/images/build_results_bar_light.png
  docs/images/build_statuses.png
  docs/images/build_statuses_light.png
  metrics/ci_integrations/docs/02_ci_integration_user_guide.md
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/04_managing_firestore_data.md
  metrics/cli/docs/05_user_manual_steps.md
  metrics/cli/lib/firebase/strings/firebase_strings.dart
  readme.md
Labels: Snake 🐍

#1357 docs: Update Firebase builds aggregation document
  metrics/firebase/docs/features/builds_aggregation/01_firestore_builds_aggregation_design.md
  metrics/firebase/docs/features/builds_aggregation/diagrams/firestore_create_builds_aggregation_sequence_diagram.puml
  metrics/firebase/docs/features/builds_aggregation/diagrams/firestore_update_builds_aggregation_sequence_diagram.puml
Labels: Snake 🐍, size/S

#1366 feat: Deployer improvements
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/firebase/strings/firebase_strings.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/strings/gcloud_strings.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/firebase/functions/package.json
Labels: size/M

#1367 fix: Update `Functions` package dependencies
  metrics/firebase/functions/pubspec.yaml
Labels: Snake 🐍, size/XS

#1368 feat: Update Github Actions to sync the build data on start
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/metrics_integration_actions.yml
  .github/workflows/web_actions.yml
Labels: size/M

#1372 feat: Improve Metrics CLI wording
  metrics/cli/lib/deploy/command/deploy_command.dart
  metrics/cli/lib/firebase/strings/firebase_strings.dart
  metrics/cli/lib/gcloud/strings/gcloud_strings.dart
  metrics/cli/lib/sentry/strings/sentry_strings.dart
Labels: Snake 🐍, size/M

#1370 feat: add GitHub action to run dart tests for firebase cloud functions
  .github/workflows/firebase_actions.yml
  .github/workflows/metrics_actions.yml
  metrics/firebase/functions/dart_test.yaml
  metrics/firebase/functions/pubspec.yaml
  metrics/firebase/functions/test/main_test.dart
Labels: size/M

#1373 refactor: Refactor onBuildAddedHandler tests
  metrics/firebase/functions/test/main_test.dart
Labels: size/L

#1378 feat: Update Firestore indexes
  metrics/firebase/firestore/indexes/firestore.indexes.json
Labels: Snake 🐍, size/S

#1379 fix: Fix web app build path
  metrics/cli/lib/deploy/model/deploy_paths.dart
Labels: Snake 🐍, size/XS

#1380 feat: Deployer prompt improvements
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/strings/deploy_strings.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/prompt/prompter.dart
  metrics/cli/lib/prompt/writer/io_prompt_writer.dart
  metrics/cli/lib/prompt/writer/prompt_writer.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/prompt/prompter_test.dart
  metrics/cli/test/prompt/writer/io_prompt_writer_test.dart
Labels: Snake 🐍, size/L

#1374 docs: Update top-level readme
  metrics/readme.md
  readme.md
Labels: size/L

#1381 docs: Fix `Metrics Web Supported Database Version` document reference
  metrics/docs/01_storing_database_metadata.md
Labels: Snake 🐍, size/XS

#1382 fix: Fix enabling analytics steps
  metrics/cli/lib/firebase/strings/firebase_strings.dart
Labels: Snake 🐍, size/S

#1387 chore: Update `firebase` package dependencies
  metrics/firebase/functions/package.json
  metrics/firebase/package.json
  metrics/firebase/test/firestore/rules/allowed-email-domains-test.js
  metrics/firebase/test/firestore/rules/build-days-test.js
  metrics/firebase/test/firestore/rules/builds-test.js
  metrics/firebase/test/firestore/rules/feature-config-test.js
  metrics/firebase/test/firestore/rules/project-groups-test.js
  metrics/firebase/test/firestore/rules/projects-test.js
  metrics/firebase/test/firestore/rules/tasks-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-app-utils.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
  metrics/firebase/test/firestore/rules/user-profiles-test.js
Labels: Snake 🐍, size/M

#1377 feat: Implement onUpdate Firestore Cloud Function trigger for build collection
  metrics/firebase/functions/index.js
  metrics/firebase/functions/lib/main.dart
  metrics/firebase/functions/lib/models/document_change_data.dart
  metrics/firebase/functions/test/main_test.dart
  metrics/firebase/functions/test/models/document_change_data_test.dart
  metrics/firebase/functions/test/models/task_code_test.dart
  metrics/firebase/functions/test/test_utils/test_data/build_test_data_generator.dart
Labels: size/XXL

#1386 feat: Migrate on `build days` collection
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/dashboard/data/repositories/firestore_metrics_repository.dart
  metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
  metrics/web/lib/dashboard/domain/repositories/metrics_repository.dart
  metrics/web/lib/dashboard/domain/usecases/receive_build_day_project_metrics_updates_stub.dart
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/dashboard/domain/usecases/receive_build_day_project_metrics_updates_stub_test.dart
  metrics/web/test/dashboard/domain/usecases/receive_project_metrics_updates_test.dart
Labels: size/L

#1402 docs: Improve repository readme
  docs/images/auth_ui.png
  docs/images/dashboard_ui_dark.png
  metrics/readme.md
  readme.md
Labels: size/M

#1393 feat: Configure Metrics CLI releases using Github Releases
  .github/workflows/cli_actions.yml
Labels: size/L

#1390 docs: Deep Links analysis document
  metrics/web/docs/analysis/deep_links/01_deep_links_analysis.md
  metrics/web/docs/analysis/deep_links/diagrams/applying_deep_links_sequence_diagram.puml
  metrics/web/docs/analysis/deep_links/diagrams/saving_deep_links_sequence_diagram.puml
Labels: size/L

#1412 fix: Fix Sentry enter release name string
  metrics/cli/docs/05_user_manual_steps.md
  metrics/cli/lib/sentry/strings/sentry_strings.dart
Labels: Snake 🐍, size/XS

#1391 docs: Update CLI design document to improve package structure
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/diagrams/cli_interfaces_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/doctor_command_class_diagram.puml
  metrics/cli/docs/diagrams/metrics_cli_runner_class_diagram.puml
  metrics/cli/docs/diagrams/prompt_class_diagram.puml
  metrics/cli/docs/diagrams/prompter_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
Labels: size/XL

#1417 fix: Fix tag name in the cli_actions
  .github/workflows/cli_actions.yml
Labels: Snake 🐍, size/XS

#1418 feat: Update GCloud CLI and Service to add delete project functionality
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/cli/gcloud_cli.dart
  metrics/cli/lib/gcloud/service/gcloud_service.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
Labels: size/M

#1413 docs: Sync performance investigatation
  metrics/ci_integrations/docs/07_sync_performance_investigation.md
  metrics/ci_integrations/docs/diagrams/sync_ideal_timing_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_problematic_queue_timing_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_problematic_timing_diagram.puml
Labels: size/L

#1420 fix: Fix top-level readme link
  readme.md
Labels: Snake 🐍, size/XS

#1407 docs: Ci integrations Supported Storage Version
  metrics/ci_integrations/docs/features/supported_storage_version/01_supported_storage_version.md
  metrics/ci_integrations/docs/features/supported_storage_version/diagrams/supported_storage_version_class_diagram.puml
  metrics/ci_integrations/docs/features/supported_storage_version/diagrams/supported_storage_version_sequence_diagram.puml
  metrics/docs/01_storing_database_metadata.md
  metrics/docs/01_storing_storage_metadata.md
  metrics/web/docs/features/supported_database_version/01_supported_database_version.md
  metrics/web/docs/features/supported_database_version/diagrams/database_finished_updating_sequence_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_data_class_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_domain_class_diagram.puml
  metrics/web/docs/features/supported_database_version/diagrams/metadata_sequence_diagram.puml
  metrics/web/docs/features/supported_storage_version/01_supported_storage_version.md
  metrics/web/docs/features/supported_storage_version/diagrams/metadata_data_class_diagram.puml
  metrics/web/docs/features/supported_storage_version/diagrams/metadata_domain_class_diagram.puml
  metrics/web/docs/features/supported_storage_version/diagrams/metadata_presentation_class_diagram.puml
  metrics/web/docs/features/supported_storage_version/diagrams/metadata_sequence_diagram.puml
  metrics/web/docs/features/supported_storage_version/diagrams/storage_finished_updating_sequence_diagram.puml
Labels: size/XXL

#1415 docs: Update the Metrics CLI readme
  docs/08_firebase_deployment.md
  docs/13_firebase_deployment_cli.md
  metrics/cli/README.md
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/images/terminal.png
  metrics/cli/recommended_versions.yaml
Labels: size/L

#1419 docs: Update Metrics readme to include installation steps
  docs/13_firebase_deployment_cli.md
  metrics/readme.md
Labels: size/S

#1427 fix: Fix links
  docs/08_firebase_deployment.md
  docs/13_firebase_deployment_cli.md
  metrics/cli/README.md
  metrics/cli/docs/01_metrics_cli_design.md
Labels: Snake 🐍, size/XS

#1426 feat: Extract `addFirebase` method in GCloudService
  metrics/cli/lib/cli/deployer/deployer.dart
  metrics/cli/lib/services/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/services/gcloud/gcloud_service.dart
  metrics/cli/test/cli/deployer/deployer_test.dart
  metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
Labels: size/L

#1428 feat: Add 'error' method to `Prompter`
  metrics/cli/lib/prompter/prompter.dart
  metrics/cli/lib/prompter/writer/io_prompt_writer.dart
  metrics/cli/lib/prompter/writer/prompt_writer.dart
  metrics/cli/test/prompter/prompter_test.dart
  metrics/cli/test/prompter/writer/io_prompt_writer_test.dart
Labels: Snake 🐍, size/M

#1429 feat: Add `Deployer` error handling
  metrics/cli/lib/cli/deployer/deployer.dart
  metrics/cli/lib/cli/deployer/strings/deploy_strings.dart
  metrics/cli/test/cli/deployer/deployer_test.dart
Labels: Snake 🐍, size/L

#1432 fix: Fix Metrics readme
  metrics/readme.md
Labels: Snake 🐍, size/M

#1434 fix: Fix Metrics CLI readme
  metrics/cli/README.md
Labels: Snake 🐍, size/XS

#1433 feat: Delete the GCloud project on Deployer fail
  metrics/cli/lib/cli/deployer/deployer.dart
  metrics/cli/lib/cli/deployer/strings/deploy_strings.dart
  metrics/cli/test/cli/deployer/deployer_test.dart
Labels: size/XL
