Repository Flank/flank-dashboard, pull requests merged in 2021-01, with the labels that each got.

#954 docs: fix typo in "properties"
  docs/18_github_actions_metrics_integration.md
Labels: Snake 🐍, size/XS

#952 feat: Implement Router
  metrics/web/lib/common/presentation/navigation/metrics_route_information_parser.dart
  metrics/web/lib/common/presentation/navigation/metrics_router_delegate.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
  metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
  metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
  metrics/web/test/test_utils/route_configuration_stub.dart
Labels: size/XL

#955 docs: Update Metrics Logger design
  metrics/web/docs/features/metrics_logger/01_metrics_logger_design.md
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_class_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_initialize_sequence_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_log_error_sequence_diagram.puml
  metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_sentry_class_diagram.puml
Labels: Snake 🐍, size/L

#956 feat: Pass user agent using EventProcessor
  metrics/web/lib/metrics_logger/sentry/event_processors/sentry_event_processor.dart
  metrics/web/lib/metrics_logger/sentry/event_processors/user_agent_event_processor.dart
  metrics/web/lib/metrics_logger/sentry/writers/sentry_writer.dart
  metrics/web/test/metrics_logger/sentry/event_processors/user_agent_event_processor_test.dart
  metrics/web/test/metrics_logger/sentry/writers/sentry_writer_test.dart
Labels: size/L

#957 feat: Integrate Metrics Logger
  metrics/web/lib/debug_menu/presentation/pages/debug_menu_page.dart
  metrics/web/lib/debug_menu/strings/debug_menu_strings.dart
  metrics/web/lib/main.dart
  metrics/web/lib/metrics_logger/writers/console_writer.dart
  metrics/web/test/debug_menu/presentation/pages/debug_menu_page_test.dart
  metrics/web/test/metrics_logger/writers/console_writer_test.dart
Labels: size/L

#959 docs: Update Build/Deployment Instructions
  docs/09_firebase_deployment.md
Labels: size/L

#958 feat: Integrate new navigation system
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
  metrics/web/lib/common/presentation/drawer/widget/metrics_drawer.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/constants/metrics_routes.dart
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page.dart
  metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_factory.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/lib/common/presentation/routes/route_generator.dart
  metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
  metrics/web/lib/common/presentation/widgets/platform_brightness_observer.dart
  metrics/web/lib/main.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/drawer/widget/metrics_drawer_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/common/presentation/routes/route_generator_test.dart
  metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
  metrics/web/test/common/presentation/widgets/platform_brightness_observer_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/test_utils/navigation_notifier_mock.dart
  metrics/web/test/test_utils/test_injection_container.dart
  metrics/web/web/index.html
Labels: size/XXL

#965 fix: Fix typo in Metrics Logger design document
  metrics/web/docs/features/metrics_logger/01_metrics_logger_design.md
Labels: Snake 🐍, size/XS

#964 docs: Update documentation to not use `flutter version`
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
  metrics/web/README.md
Labels: size/M

#966 feat: Firebase auto config
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
  metrics/web/__/firebase/init.js
  metrics/web/web/index.html
Labels: Snake 🐍, size/L

#973 build: Update Flutter version, fix driver tests
  .github/workflows/ci_integrations_actions.yml
  .github/workflows/coverage_converter_actions.yml
  .github/workflows/metrics_actions.yml
  .github/workflows/web_actions.yml
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
  docs/15_developer_configuration.md
  metrics/web/README.md
  metrics/web/test_driver/cli/common/process/process_wrapper.dart
  metrics/web/test_driver/cli/flutter/runner/flutter_drive_process_runner.dart
  metrics/web/test_driver/process_manager/process_manager.dart
Labels: Snake 🐍, size/L

#972 feat: Introduce Metrics Config
  .github/workflows/web_actions.yml
  docs/09_firebase_deployment.md
  docs/16_dependencies_licenses.md
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/common/domain/entities/metrics_config.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/main.dart
  metrics/web/lib/metrics_logger/sentry/writers/sentry_writer.dart
  metrics/web/lib/platform/stub/metrics_config/metrics_config_factory.dart
  metrics/web/lib/platform/web/metrics_config/metrics_config_factory.dart
  metrics/web/lib/platform/web/metrics_config/web_metrics_config.dart
  metrics/web/pubspec.yaml
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/metrics_logger/sentry/writers/sentry_writer_test.dart
  metrics/web/test/test_utils/metrics_config_stub.dart
  metrics/web/test_driver/app_test.dart
  metrics/web/web/index.html
  metrics/web/web/metrics_config.js
Labels: size/XL

#976 fix: Environment Variable substitution in actions
  .github/workflows/web_actions.yml
Labels: Snake 🐍, size/XS

#977 fix: Lint sort_pub_dependencies
  metrics/core/pubspec.yaml
Labels: Snake 🐍, size/XS

#967 fix: Fix navigation to be able to go back from the loading screen
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_state.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/lib/main.dart
  metrics/web/lib/platform/stub/platform_configuration/platform_configuration_stub.dart
  metrics/web/lib/platform/web/browser_navigation_state/browser_navigation_state.dart
  metrics/web/lib/platform/web/platform_configuration/web_platform_configuration.dart
  metrics/web/pubspec.lock
  metrics/web/pubspec.yaml
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
  metrics/web/test/platform/web/browser_navigation_state/browser_navigation_state_test.dart
  metrics/web/test/test_utils/history_mock.dart
  metrics/web/test/test_utils/navigation_state_mock.dart
  metrics/web/test/test_utils/router_delegate_stub.dart
  metrics/web/test_driver/app_test.dart
  metrics/web/web/index.html
Labels: size/XL

#979 fix: Fix Firebase routing
  metrics/web/firebase.json
Labels: Snake 🐍, size/S

#980 docs: CI Integrations verbose mode design
  metrics/ci_integrations/docs/03_ci_integration_verbose_mode.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_verbose_mode_diagram.puml
Labels: size/L

#978 docs: Searchable Dropdown design document
  metrics/web/docs/features/searchable_dropdown/01_searchable_dropdown_design.md
  metrics/web/docs/features/searchable_dropdown/diagrams/project_groups_searchable_dropdown_widget_class_diagram.puml
  metrics/web/docs/features/searchable_dropdown/diagrams/searchable_dropdown_widget_class_diagram.puml
Labels: size/L

#985 build: Automatic deployments to production
  .github/workflows/web_actions.yml
Labels: size/M

#969 docs: Create Metrics CLI diagrams
  metrics/deploy/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/deploy/docs/diagrams/deploy_tool_class_diagram.puml
  metrics/deploy/docs/diagrams/doctor_command_sequence_diagram.puml
Labels: size/L

#971 docs: Security Audit document
  docs/09_firebase_deployment.md
  docs/19_security_audit_document.md
Labels: size/L

#991 build: Simplify Firebase hosting targets
  .github/workflows/web_actions.yml
  metrics/web/.firebaserc
  metrics/web/firebase.json
Labels: size/M

#996 fix: Fix Production deploy command
  .github/workflows/web_actions.yml
Labels: Snake 🐍, size/XS

#989 feat: CI Integrations: Add verbose mode
  docs/16_dependencies_licenses.md
  metrics/ci_integrations/bin/main.dart
  metrics/ci_integrations/lib/cli/command/ci_integration_command.dart
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/cli/logger/logger.dart
  metrics/ci_integrations/lib/cli/runner/ci_integration_runner.dart
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/pubspec.yaml
  metrics/ci_integrations/test/cli/command/ci_integration_command_test.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/logger/logger_test.dart
  metrics/ci_integrations/test/cli/runner/ci_integration_runner_test.dart
  metrics/ci_integrations/test/cli/test_util/mock/io_sink_mock.dart
  metrics/ci_integrations/test/cli/test_util/stub/logger_stub.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
  metrics/ci_integrations/test/destination/firestore/client_factory/firestore_destination_client_factory_test.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/XL

#1003 fix: Remove Logger tests
  metrics/ci_integrations/test/cli/logger/logger_test.dart
Labels: Snake 🐍, size/S

#994 fix: Large builds per week numbers
  docs/16_dependencies_licenses.md
  metrics/web/lib/base/presentation/widgets/scorecard.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/widgets/scorecard_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_number_scorecard_test.dart
Labels: size/L

#1005 docs: Update deployment documents with `target` instructions
  docs/09_firebase_deployment.md
  docs/14_firebase_deployment_cli.md
Labels: size/M

#1004 feat: Consider using `flutterCanvasKit` to detect the application's renderer
  metrics/web/lib/base/presentation/widgets/icon_label_button.dart
  metrics/web/lib/base/presentation/widgets/svg_image.dart
  metrics/web/lib/base/presentation/widgets/tappable_area.dart
  metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
  metrics/web/lib/debug_menu/presentation/state/debug_menu_notifier.dart
  metrics/web/lib/platform/stub/renderer/renderer_stub.dart
  metrics/web/lib/platform/web/renderer/web_renderer.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/auth/presentation/widgets/password_sign_in_option_test.dart
  metrics/web/test/auth/presentation/widgets/sign_in_option_button_test.dart
  metrics/web/test/base/presentation/widgets/svg_image_test.dart
  metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
  metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart
  metrics/web/test/common/presentation/tooltip_icon/widgets/tooltip_icon_test.dart
  metrics/web/test/common/presentation/user_menu_button/widgets/metrics_user_menu_button_test.dart
  metrics/web/test/common/presentation/value_image/widgets/value_network_image_test.dart
  metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
  metrics/web/test/common/presentation/widgets/metrics_theme_image_test.dart
  metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
  metrics/web/test/debug_menu/presentation/state/debug_menu_notifier_test.dart
  metrics/web/test/debug_menu/presentation/widgets/debug_menu_renderer_display_test.dart
  metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
  metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
  metrics/web/test/test_utils/finder_util.dart
  metrics/web/test/test_utils/renderer_mock.dart
Labels: size/L

#1007 feat: Improve coverage metric description
  metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
Labels: Snake 🐍, size/XS

#990 docs: CI Integrations Config Validator design document
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml
Labels: size/L

#1010 feat: CI integrations Logger improvements
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/cli/logger/factory/logger_factory.dart
  metrics/ci_integrations/lib/cli/logger/logger.dart
  metrics/ci_integrations/lib/cli/logger/manager/logger_manager.dart
  metrics/ci_integrations/lib/cli/logger/mixin/logger_mixin.dart
  metrics/ci_integrations/lib/cli/logger/writer/io_logger_writer.dart
  metrics/ci_integrations/lib/cli/logger/writer/logger_writer.dart
  metrics/ci_integrations/lib/cli/runner/ci_integration_runner.dart
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
  metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/logger/factory/logger_factory_test.dart
  metrics/ci_integrations/test/cli/logger/logger_test.dart
  metrics/ci_integrations/test/cli/logger/manager/logger_manager_test.dart
  metrics/ci_integrations/test/cli/logger/mixin/logger_mixin_test.dart
  metrics/ci_integrations/test/cli/logger/writer/io_logger_writer_test.dart
  metrics/ci_integrations/test/cli/runner/ci_integration_runner_test.dart
  metrics/ci_integrations/test/cli/test_util/mock/io_sink_mock.dart
  metrics/ci_integrations/test/cli/test_util/mock/logger_factory_mock.dart
  metrics/ci_integrations/test/cli/test_util/mock/logger_writer_mock.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
  metrics/ci_integrations/test/destination/firestore/client_factory/firestore_destination_client_factory_test.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
Labels: size/XL

#1009 docs: CI Integrations: design additional parameter to skip-coverage
  metrics/ci_integrations/docs/01_ci_integration_module_architecture.md
  metrics/ci_integrations/docs/02_ci_integration_user_guide.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_class_diagram.puml
Labels: size/L

#1012 feat: Add `skip-coverage` flag to sync command
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/cli/runner/ci_integration_runner.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/integration/ci/config/model/sync_config.dart
  metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
  metrics/ci_integrations/test/integration/ci/ci_integration_test.dart
  metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart
  metrics/ci_integrations/test/integration/ci/test_utils/stub/source_client_stub.dart
  metrics/core/lib/src/data/model/build_data.dart
  metrics/core/lib/src/domain/entities/build.dart
  metrics/core/test/data/model/build_data_test.dart
Labels: size/L

#1023 fix: Update Firestore Security rules
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/builds-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: Snake 🐍, size/M

#1025 feat: Buildkite fetch coverage
  .github/workflows/metrics_actions.yml
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/client/buildkite/models/buildkite_build.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/test/client/buildkite/models/buildkite_build_test.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart
Labels: size/XL

#1022 feat: Implement Config Validation base classes and interfaces
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml
  metrics/ci_integrations/lib/integration/error/config_validation_error.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validation_delegate/validation_delegate.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validator/config_validator.dart
  metrics/ci_integrations/lib/integration/interface/base/config/validator_factory/config_validator_factory.dart
  metrics/ci_integrations/lib/integration/interface/destination/config/validation_delegate/destination_validation_delegate.dart
  metrics/ci_integrations/lib/integration/interface/source/config/validation_delegate/source_validation_delegate.dart
  metrics/ci_integrations/pubspec.yaml
  metrics/ci_integrations/test/integration/error/config_validation_error_test.dart
  metrics/ci_integrations/test/integration/interface/base/config/validator/config_validator_test.dart
Labels: size/L

#1026 fix: Builds on latest Flutter master
  metrics/web/pubspec.yaml
Labels: Snake 🐍, size/XS

#1011 feat: Pass fetch limit as an argument
  metrics/ci_integrations/docs/02_ci_integration_user_guide.md
  metrics/ci_integrations/lib/cli/command/sync_command.dart
  metrics/ci_integrations/lib/integration/ci/ci_integration.dart
  metrics/ci_integrations/lib/integration/ci/config/model/sync_config.dart
  metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
  metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
  metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
  metrics/ci_integrations/lib/util/validator/number_validator.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
  metrics/ci_integrations/test/integration/ci/ci_integration_test.dart
  metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart
  metrics/ci_integrations/test/integration/ci/test_utils/stub/source_client_stub.dart
  metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
  metrics/ci_integrations/test/util/validator/number_validator_test.dart
Labels: size/XL

#1027 feat: Add production sync pipeline
  .buildkite/pipelines/prod_sync_pipeline.yml
  .metrics/buildkite/prod_integration_config.yml
Labels: Snake 🐍, size/S

#1028 fix: Change names of Environment Variables
  .metrics/buildkite/prod_integration_config.yml
Labels: Snake 🐍, size/XS
