Repository Flank/flank-dashboard, pull requests merged in 2021-03, with the labels that each got.

#1128 feat: Extend Github Actions client to include validation-required methods
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/models/github_token.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/github_actions/models/github_token_test.dart
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
Labels: size/L

#1135 docs: Commands code sharing design document
  metrics/ci_integrations/docs/05_ci_integration_commands_code_sharing.md
  metrics/ci_integrations/docs/diagrams/commands_code_sharing.puml
Labels: size/L

#1144 feat: Implement RawIntegrationConfigFactory
  metrics/ci_integrations/lib/cli/config/factory/raw_integration_config_factory.dart
  metrics/ci_integrations/lib/util/file/file_helper.dart
  metrics/ci_integrations/lib/util/file/file_reader.dart
  metrics/ci_integrations/test/cli/config/factory/raw_integration_config_factory_test.dart
  metrics/ci_integrations/test/util/file/file_reader_test.dart
Labels: size/L

#1142 docs: Animation handoff investigation document
  metrics/web/docs/analysis/01_animation_library_approaches.md
Labels: size/L

#1148 feat: Implement ConfiguredParty, ConfiguredSourceParty and ConfiguredDestinationParty
  metrics/ci_integrations/lib/cli/configured_parties/configured_destination_party.dart
  metrics/ci_integrations/lib/cli/configured_parties/configured_party.dart
  metrics/ci_integrations/lib/cli/configured_parties/configured_source_party.dart
  metrics/ci_integrations/test/cli/configured_parties/configured_destination_party_test.dart
  metrics/ci_integrations/test/cli/configured_parties/configured_party_test.dart
  metrics/ci_integrations/test/cli/configured_parties/configured_source_party_test.dart
  metrics/ci_integrations/test/cli/test_util/destination_config_stub.dart
  metrics/ci_integrations/test/cli/test_util/destination_party_stub.dart
  metrics/ci_integrations/test/cli/test_util/source_config_stub.dart
  metrics/ci_integrations/test/cli/test_util/source_party_stub.dart
Labels: size/L

#1145 fix: Remove Validation Delegate abstract class
  metrics/ci_integrations/lib/integration/interface/base/config/validation_delegate/validation_delegate.dart
  metrics/ci_integrations/lib/integration/interface/destination/config/validation_delegate/destination_validation_delegate.dart
  metrics/ci_integrations/lib/integration/interface/source/config/validation_delegate/source_validation_delegate.dart
  metrics/ci_integrations/lib/integration/stub/base/config/validation_delegate/validation_delegate_stub.dart
  metrics/ci_integrations/lib/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
  metrics/ci_integrations/test/integration/stub/base/config/validation_delegate/validation_delegate_stub_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
Labels: Snake 🐍, size/L

#1119 docs: CI integrations sync doc
  metrics/ci_integrations/docs/05_builds_synchronization.md
  metrics/ci_integrations/docs/diagrams/add_coverage_data_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_builds_stage_activity_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_builds_stage_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_single_build_activity_diagram.puml
  metrics/ci_integrations/docs/diagrams/resync_single_build_sequence_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_algorithm_activity_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_algorithm_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_builds_stage_activity_diagram.puml
  metrics/ci_integrations/docs/diagrams/sync_builds_stage_sequence_diagram.puml
Labels: size/XL

#1155 fix: Document order number
  metrics/ci_integrations/docs/06_builds_synchronization.md
Labels: Snake 🐍

#1149 feat: Implement Create ConfiguredParties and ConfiguredPartiesFactory
  metrics/ci_integrations/lib/cli/configured_parties/configured_parties.dart
  metrics/ci_integrations/lib/cli/configured_parties/factory/configured_parties_factory.dart
  metrics/ci_integrations/lib/cli/parties/parties.dart
  metrics/ci_integrations/lib/cli/parties/supported_destination_parties.dart
  metrics/ci_integrations/lib/cli/parties/supported_source_parties.dart
  metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
  metrics/ci_integrations/lib/integration/interface/base/party/integration_party.dart
  metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/cli/configured_parties/configured_parties_test.dart
  metrics/ci_integrations/test/cli/configured_parties/configured_party_test.dart
  metrics/ci_integrations/test/cli/configured_parties/factory/configured_parties_factory_test.dart
  metrics/ci_integrations/test/cli/parties/parties_test.dart
  metrics/ci_integrations/test/cli/test_util/destination_party_stub.dart
  metrics/ci_integrations/test/cli/test_util/mock/config_parser_mock.dart
  metrics/ci_integrations/test/cli/test_util/source_party_stub.dart
  metrics/ci_integrations/test/integration/interface/base/party/integration_party_test.dart
Labels: size/XL

#1151 feat: Implement Github Actions Source Validation Delegate
  metrics/ci_integrations/lib/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
  metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/github_actions/test_utils/github_actions_client_mock.dart
Labels: size/XL

#1154 feat: Implement ValidationResultPrinter
  metrics/ci_integrations/lib/integration/validation/printer/validation_result_printer.dart
  metrics/ci_integrations/test/cli/logger/writer/io_logger_writer_test.dart
  metrics/ci_integrations/test/integration/validation/printer/validation_result_printer_test.dart
  metrics/ci_integrations/test/test_utils/mock/io_sink_mock.dart
Labels: size/L

#1165 feat: Extend Jenkins client to include validation-required methods
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_user.dart
  metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_user_test.dart
  metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
  metrics/ci_integrations/test/client/test_utils/mock_server_utils.dart
Labels: size/L

#1166 test: Improve tests for Buildkite Source Validator
  metrics/ci_integrations/lib/source/buildkite/config/validator_factory/buildkite_source_validator_factory.dart
  metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
  metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator_factory/buildkite_source_validator_factory_test.dart
  metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart
Labels: Snake 🐍, size/S

#1167 feat: Implement Prompter.
  metrics/cli/lib/prompt/prompter.dart
  metrics/cli/lib/prompt/writer/prompt_writer.dart
  metrics/cli/pubspec.yaml
  metrics/cli/test/prompt/prompter_test.dart
Labels: size/L

#1161 docs: Create a document for the user’s manual steps
  metrics/cli/docs/05_user_manual_steps.md
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
Labels: size/L

#1169 feat: Implement base interfaces
  metrics/cli/lib/interfaces/cli/cli.dart
  metrics/cli/lib/interfaces/service/info_service.dart
Labels: size/S

#1168 feat: Implement Jenkins Source Validation Delegate
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/jenkins/strings/jenkins_strings.dart
  metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
  metrics/ci_integrations/test/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/jenkins/test_utils/jenkins_client_mock.dart
Labels: size/L

#1162 feat: Implement Github Actions Source Validation Delegate
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
  metrics/ci_integrations/lib/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
  metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
  metrics/ci_integrations/test/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate_test.dart
Labels: size/XXL

#1172 feat: Implement Firestore Validation Models required for Config Validation
  metrics/ci_integrations/lib/client/firestore/mappers/firestore_exception_reason_mapper.dart
  metrics/ci_integrations/lib/client/firestore/models/firebase_auth_credentials.dart
  metrics/ci_integrations/lib/client/firestore/models/firestore_exception_reason.dart
  metrics/ci_integrations/test/client/firestore/mappers/firestore_exception_reason_mapper_test.dart
  metrics/ci_integrations/test/client/firestore/models/firebase_auth_credentials_test.dart
Labels: size/L

#1173 feat: Implement IOPromptWriter
  metrics/cli/docs/01_metrics_cli_design.md
  metrics/cli/docs/diagrams/prompt_class_diagram.puml
  metrics/cli/lib/prompt/prompter.dart
  metrics/cli/lib/prompt/writer/io_prompt_writer.dart
  metrics/cli/lib/prompt/writer/prompt_writer.dart
  metrics/cli/test/prompt/prompter_test.dart
  metrics/cli/test/prompt/writer/io_prompt_writer_test.dart
Labels: size/L

#1170 feat: Implement GithubActionsSourceConfigValidator, GithubActionsSourceConfigValidatorFactory
  metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
  metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
  metrics/ci_integrations/lib/source/github_actions/config/model/github_actions_source_config_field.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator_factory/github_actions_source_validator_factory.dart
  metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
  metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/source/github_actions/config/model/github_actions_source_config_field_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validator_factory/github_actions_source_validator_factory_test.dart
  metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart
Labels: size/XXL

#1183 docs: Web in-progress builds
  metrics/web/docs/features/in_progress_builds/01_in_progress_builds_introduction.md
  metrics/web/docs/features/in_progress_builds/diagrams/build_core_class_diagram.puml
  metrics/web/docs/features/in_progress_builds/diagrams/data_layer_class_diagram.puml
  metrics/web/docs/features/in_progress_builds/diagrams/domain_layer_class_diagram.puml
  metrics/web/docs/features/in_progress_builds/diagrams/presentation_layer_class_diagram.puml
  metrics/web/docs/features/in_progress_builds/diagrams/presentation_layer_strategies_class_diagram.puml
  metrics/web/docs/features/in_progress_builds/diagrams/presentation_layer_widgets_class_diagram.puml
Labels: size/XL

#1185 docs: Update Config Validator with new validation result
  metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
  metrics/ci_integrations/docs/diagrams/config_validator_base_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/config_validator_destination_class_diagram.puml
  metrics/ci_integrations/docs/diagrams/config_validator_sequence_diagram.puml
Labels: size/L

#1184 feat: Implement FlutterCLI
  metrics/cli/docs/diagrams/cli_interfaces_class_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/flutter/cli/flutter_cli.dart
  metrics/cli/lib/interfaces/cli/cli.dart
Labels: size/M

#1186 feat: Implement GithubActionsSourceConfigValidator
  metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
  metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
  metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
Labels: size/L

#1198 feat: Update BuildkiteSourceValidationDelegate to match the latest designs
  metrics/ci_integrations/lib/integration/validation/model/field_validation_result.dart
  metrics/ci_integrations/lib/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
  metrics/ci_integrations/test/integration/validation/model/field_validation_result_test.dart
  metrics/ci_integrations/test/integration/validation/printer/validation_result_printer_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
Labels: size/XL

#1200 feat: Implement GitCli
  docs/16_dependencies_licenses.md
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/flutter/cli/flutter_cli.dart
  metrics/cli/lib/git/cli/git_cli.dart
Labels: size/M

#1202 feat: Implement NpmCli
  metrics/cli/lib/npm/cli/npm_cli.dart
Labels: size/S

#1204 feat: Update JenkinsSourceValidationDelegate to match the latest designs
  metrics/ci_integrations/lib/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate.dart
  metrics/ci_integrations/test/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate_test.dart
Labels: size/L

#1201 feat: Implement GCloudCli
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/gcloud/cli/gcloud_cli.dart
Labels: size/M

#1205 feat: Implement FirebaseCli
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/firebase/cli/firebase_cli.dart
Labels: size/M

#1206 feat: Implement Jenkins SourceValidator and SourceValidatorFactory
  metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
  metrics/ci_integrations/lib/source/buildkite/config/validator_factory/buildkite_source_validator_factory.dart
  metrics/ci_integrations/lib/source/jenkins/client_factory/jenkins_source_client_factory.dart
  metrics/ci_integrations/lib/source/jenkins/config/model/jenkins_source_config_field.dart
  metrics/ci_integrations/lib/source/jenkins/config/validator/jenkins_source_validator.dart
  metrics/ci_integrations/lib/source/jenkins/config/validator_factory/jenkins_source_validator_factory.dart
  metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
  metrics/ci_integrations/lib/source/jenkins/strings/jenkins_strings.dart
  metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
  metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
  metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
  metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
  metrics/ci_integrations/test/source/jenkins/config/model/jenkins_source_config_field_test.dart
  metrics/ci_integrations/test/source/jenkins/config/validator/jenkins_source_validator_test.dart
  metrics/ci_integrations/test/source/jenkins/config/validator_factory/jenkins_source_validator_factory_test.dart
  metrics/ci_integrations/test/source/jenkins/party/jenkins_source_party_test.dart
  metrics/ci_integrations/test/test_utils/mock/validation_result_builder_mock.dart
Labels: size/XL

#1207 feat: Implement FirestoreDestinationValidationDelegate
  metrics/ci_integrations/lib/destination/firestore/config/validation_delegate/firestore_destination_validation_delegate.dart
  metrics/ci_integrations/lib/destination/firestore/factory/firebase_auth_factory.dart
  metrics/ci_integrations/lib/destination/firestore/strings/firestore_strings.dart
  metrics/ci_integrations/lib/source/buildkite/strings/buildkite_strings.dart
  metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
  metrics/ci_integrations/lib/source/jenkins/strings/jenkins_strings.dart
  metrics/ci_integrations/test/cli/command/sync_command_test.dart
  metrics/ci_integrations/test/destination/firestore/client_factory/firestore_destination_client_factory_test.dart
  metrics/ci_integrations/test/destination/firestore/config/validation_delegate/firestore_destination_validation_delegate_test.dart
  metrics/ci_integrations/test/destination/firestore/factory/firebase_auth_factory_test.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/mock/firebase_auth_mock.dart
Labels: size/XL

#1211 feat: Update GithubActionsSourceValidationDelegate to match the latest designs
  metrics/ci_integrations/lib/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate.dart
  metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
  metrics/ci_integrations/test/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate_test.dart
  metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
Labels: size/XXL

#1212 ci: Add Github Actions for Metrics CLI
  .github/workflows/cli_actions.yml
  .github/workflows/metrics_actions.yml
Labels: size/M

#1214 docs: Update CI Integrations User Guide with the `validate` command
  metrics/ci_integrations/docs/02_ci_integration_user_guide.md
Labels: size/M

#1215 feat: Update Firestore Destination Validation Delegate
  metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
  metrics/ci_integrations/lib/destination/firestore/config/validation_delegate/firestore_destination_validation_delegate.dart
  metrics/ci_integrations/lib/destination/firestore/factory/firebase_auth_factory.dart
  metrics/ci_integrations/lib/destination/firestore/factory/firestore_factory.dart
  metrics/ci_integrations/lib/destination/firestore/strings/firestore_strings.dart
  metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
  metrics/ci_integrations/test/destination/firestore/config/validation_delegate/firestore_destination_validation_delegate_test.dart
  metrics/ci_integrations/test/destination/firestore/factory/firestore_factory_test.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/test_data/collection_reference_mock.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/test_data/document_mock.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/test_data/document_reference_mock.dart
  metrics/ci_integrations/test/destination/firestore/test_utils/test_data/firestore_mock.dart
Labels: Snake 🐍, size/XL

#1220 fix: Fix analyzer warnings
  metrics/cli/lib/deploy/deploy_command.dart
  metrics/cli/test/deploy/deploy_command_test.dart
Labels: Snake 🐍, size/XS

#1224 fix: Update Prompter to match design
  metrics/cli/lib/prompt/prompter.dart
  metrics/cli/test/prompt/prompter_test.dart
Labels: Snake 🐍, size/M

#1219 feat: Implement Firestore DestinationConfigValidator and DestinationConfigValidatorFactory
  metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config_field.dart
  metrics/ci_integrations/lib/destination/firestore/config/validator/firestore_destination_validator.dart
  metrics/ci_integrations/lib/destination/firestore/config/validator_factory/firestore_destination_validator_factory.dart
  metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
  metrics/ci_integrations/lib/destination/firestore/strings/firestore_strings.dart
  metrics/ci_integrations/test/destination/firestore/config/model/firestore_destination_config_field_test.dart
  metrics/ci_integrations/test/destination/firestore/config/validator/firestore_destination_validator_test.dart
  metrics/ci_integrations/test/destination/firestore/config/validator_factory/firestore_destination_validator_factory_test.dart
  metrics/ci_integrations/test/destination/firestore/party/firestore_destination_party_test.dart
Labels: size/XL

#1222 feat: Update BuildStatus enum to include inProgress status
  metrics/core/lib/src/domain/entities/build_status.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_image_strategy.dart
  metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_popup_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_image_strategy_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart
  metrics/web/web/icons/in_progress.svg
  metrics/web/web/icons/in_progress_status.svg
Labels: size/L

#1225 feat: Update Performance and Stability metrics calculation
  metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
  metrics/web/test/dashboard/domain/usecases/receive_project_metrics_updates_test.dart
Labels: size/L

#1221 feat: Implement GCloudService
  docs/16_dependencies_licenses.md
  metrics/cli/lib/flutter/adapter/flutter_cli_service_adapter.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/service/gcloud_service.dart
  metrics/cli/lib/gcloud/strings/gcloud_strings.dart
  metrics/cli/pubspec.yaml
  metrics/cli/test/flutter/adapter/flutter_cli_service_adapter_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/prompt/prompter_test.dart
  metrics/cli/test/test_utils/prompt_writer_mock.dart
  metrics/cli/test/test_utils/prompter_mock.dart
Labels: size/L

#1226 feat: Implement SentryCLI
  metrics/cli/lib/sentry/cli/sentry_cli.dart
  metrics/cli/lib/sentry/model/sentry_project.dart
  metrics/cli/test/sentry/model/sentry_project_test.dart
Labels: size/L

#1228 feat: Implement TimerNotifier
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/dashboard/presentation/state/timer_notifier.dart
  metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
  metrics/web/test/dashboard/presentation/state/timer_notifier_test.dart
Labels: size/L

#1238 fix: Fix Firebase Auth Initialization
  metrics/ci_integrations/lib/destination/firestore/factory/firebase_auth_factory.dart
Labels: Snake 🐍, size/XS

#1237 feat: Implement FileHelper
  metrics/cli/docs/diagrams/deploy_command_class_diagram.puml
  metrics/cli/docs/diagrams/deploy_command_sequence_diagram.puml
  metrics/cli/docs/diagrams/services_class_diagram.puml
  metrics/cli/lib/helper/file_helper.dart
  metrics/cli/test/helper/file_helper_test.dart
Labels: size/L

#1241 fix: Fix Jenkins Url Validation
  metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
  metrics/ci_integrations/lib/client/jenkins/model/jenkins_instance_info.dart
  metrics/ci_integrations/test/client/jenkins/model/jenkins_instance_info_test.dart
Labels: Snake 🐍, size/M

#1239 docs: Firestore emulator analysis doc
  metrics/web/docs/analysis/02_firestore_emulator_for_driver_tests.md
Labels: size/L

#1236 feat: Implement view models for finished and in-progress builds
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/finished_build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/view_models/in_progress_build_result_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/finished_build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/view_models/in_progress_build_result_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
Labels: size/XL

#1243 feat: Update BuildResultPopupCard and ViewModel
  metrics/web/lib/dashboard/presentation/view_models/build_result_popup_view_model.dart
  metrics/web/lib/dashboard/presentation/widgets/build_result_popup_card.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_popup_view_model_test.dart
  metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart
Labels: size/L

#1242 feat: Implement ServicesFactory
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/common/model/services.dart
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/services_test.dart
Labels: size/L

#1244 feat: Implement BuildResultDurationStrategy
  metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_duration_strategy.dart
  metrics/web/test/dashboard/presentation/widgets/strategy/build_result_duration_strategy_test.dart
Labels: size/M

#1248 feat: Update BuildResultViewModel mapping
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
Labels: Snake 🐍, size/L

#1249 feat: Implement Deployer
  metrics/cli/lib/cli/firebase/firebase_command.dart
  metrics/cli/lib/common/factory/services_factory.dart
  metrics/cli/lib/deploy/constants/deploy_constants.dart
  metrics/cli/lib/deploy/deployer.dart
  metrics/cli/lib/deploy/factory/deployer_factory.dart
  metrics/cli/lib/firebase/cli/firebase_cli.dart
  metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
  metrics/cli/lib/gcloud/cli/gcloud_cli.dart
  metrics/cli/test/common/factory/services_factory_test.dart
  metrics/cli/test/common/model/services_test.dart
  metrics/cli/test/deploy/deployer_test.dart
  metrics/cli/test/deploy/factory/deployer_factory_test.dart
  metrics/cli/test/flutter/adapter/flutter_cli_service_adapter_test.dart
  metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
  metrics/cli/test/helper/file_helper_test.dart
  metrics/cli/test/test_utils/directory_mock.dart
  metrics/cli/test/test_utils/flutter_service_mock.dart
  metrics/cli/test/test_utils/gcloud_service_mock.dart
Labels: size/XL

#1247 feat: Implement RiveAnimation and RiveArtboardFactory
  docs/16_dependencies_licenses.md
  metrics/web/lib/base/presentation/widgets/factory/rive_artboard_factory.dart
  metrics/web/lib/base/presentation/widgets/rive_animation.dart
  metrics/web/pubspec.yaml
  metrics/web/test/base/presentation/test_data/rive_animation_test_data.dart
  metrics/web/test/base/presentation/widgets/factory/rive_artboard_factory_test.dart
  metrics/web/test/base/presentation/widgets/rive_animation_test.dart
  metrics/web/test/test_utils/asset_bundle_mock.dart
Labels: size/XL
