Repository Flank/flank-dashboard, pull requests merged in 2021-08, with the labels that each got.

#1543 feat: Handling deep links that require authorization
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
  metrics/web/lib/common/presentation/pages/loading_page.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
  metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
  metrics/web/test/common/presentation/pages/loading_page_test.dart
Labels: size/XL

#1544 feat: Apply filters to deep links
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_location_converter.dart
  metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
  metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_location_converter_test.dart
  metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
  metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
  metrics/web/test/test_utils/project_metrics_notifier_stub.dart
Labels: size/L

#1545 feat: Update Doctor with Dependencies
  metrics/cli/lib/cli/doctor/constants/doctor_constants.dart
  metrics/cli/lib/cli/doctor/doctor.dart
  metrics/cli/lib/cli/doctor/factory/doctor_factory.dart
  metrics/cli/test/cli/doctor/doctor_test.dart
  metrics/cli/test/cli/doctor/factory/doctor_factory_test.dart
  metrics/cli/test/test_utils/mocks/dependencies_factory_mock.dart
  metrics/cli/test/test_utils/mocks/dependencies_mock.dart
Labels: size/L

#1547 fix: Build skia app using the current Flutter version
  .github/workflows/web_actions.yml
Labels: size/XS, Snake 🐍

#1549 feat: ManufacturerBanner theme data
  metrics/web/lib/common/presentation/manufacturer_banner/theme/theme_data/manufacturer_banner_theme_data.dart
  metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
  metrics/web/lib/common/presentation/metrics_theme/config/metrics_colors.dart
  metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
  metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
  metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
  metrics/web/test/common/presentation/manufacturer_banner/theme/theme_data/manufacturer_banner_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
  metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
Labels: size/L

#1540 docs: Create the design section for the public dashboard feature
  metrics/web/docs/features/public_dashboard/01_public_dashboard.md
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_architecture_components_diagram.puml
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_auth_class_diagram.puml
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_class_diagram.puml
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_feature_config_class_diagram.puml
  metrics/web/docs/features/public_dashboard/diagrams/public_dashboard_sequence_diagram.puml
  metrics/web/docs/features/public_dashboard/images/menu.png
Labels: size/XL

#1552 feat: Implement MaterialContainer
  metrics/web/lib/base/presentation/widgets/material_container.dart
  metrics/web/test/base/presentation/widgets/material_container_test.dart
Labels: size/L

#1568 feat: Change the FeatureConfig entity and the FeatureConfigData model
  metrics/web/lib/feature_config/data/model/feature_config_data.dart
  metrics/web/lib/feature_config/domain/entities/feature_config.dart
  metrics/web/test/feature_config/data/model/feature_config_data_test.dart
  metrics/web/test/feature_config/domain/entities/feature_config_test.dart
Labels: size/M

#1569 feat: Add the sign-in anonymously feature to the FirebaseUserRepository
  metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
  metrics/web/lib/auth/domain/repositories/user_repository.dart
Labels: size/S

#1573 feat: Change the Presentation layer of the FeatureConfig module #1554
  metrics/web/lib/feature_config/domain/usecases/fetch_feature_config_usecase.dart
  metrics/web/lib/feature_config/domain/usecases/parameters/feature_config_param.dart
  metrics/web/lib/feature_config/presentation/models/public_dashboard_feature_config_model.dart
  metrics/web/lib/feature_config/presentation/state/feature_config_notifier.dart
  metrics/web/test/feature_config/domain/usecases/fetch_feature_config_usecase_test.dart
  metrics/web/test/feature_config/domain/usecases/parameters/feature_config_param_test.dart
  metrics/web/test/feature_config/presentation/models/public_dashboard_feature_config_model_test.dart
  metrics/web/test/feature_config/presentation/state/feature_config_notifier_test.dart
  metrics/web/test/test_utils/feature_config_notifier_stub.dart
Labels: size/L

#1572 feat: Change the RouteConfiguration class
  metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
  metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_test.dart
Labels: size/M

#1574 feat: Implement AuthState enum and integrate it
  metrics/web/lib/auth/data/adapter/firebase_user_adapter.dart
  metrics/web/lib/auth/domain/entities/user.dart
  metrics/web/lib/auth/presentation/models/auth_state.dart
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/test/auth/data/adapter/firebase_user_adapter_test.dart
  metrics/web/test/auth/domain/entities/user_test.dart
  metrics/web/test/auth/presentation/state/auth_notifier_test.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/L

#1576 fix: Fix login screen overflow
  metrics/web/lib/auth/presentation/pages/login_page.dart
Labels: size/M

#1571 feat: Implement Doctor versions checking models
  metrics/cli/lib/cli/doctor/models/doctor_target_validation_result.dart
  metrics/cli/lib/cli/doctor/models/doctor_validation_conclusion.dart
  metrics/cli/lib/cli/doctor/strings/doctor_strings.dart
  metrics/cli/test/cli/doctor/models/doctor_target_validation_result_test.dart
  metrics/cli/test/cli/doctor/models/doctor_validation_conclusion_test.dart
Labels: size/XL

#1582 fix: Fix login page scroll #1576
  metrics/web/lib/auth/presentation/pages/login_page.dart
Labels: size/M

#1578 feat: Subscribe AuthNotifier on the FeatureConfig updates
  metrics/web/lib/auth/presentation/state/auth_notifier.dart
  metrics/web/lib/common/presentation/injector/widget/injection_container.dart
  metrics/web/lib/feature_config/presentation/state/feature_config_notifier.dart
  metrics/web/test/test_utils/auth_notifier_stub.dart
  metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
Labels: size/M

#1579 feat: Implement the use case class for the anonymous sign-in
  metrics/web/lib/auth/domain/usecases/sign_in_anonymously_usecase.dart
  metrics/web/test/auth/domain/usercases/sign_in_anonymously_usecase_test.dart
Labels: size/M

#1584 feat: Cancel the anonymous user redirection from the LoginPage
  metrics/web/lib/auth/presentation/pages/login_page.dart
  metrics/web/test/auth/presentation/pages/login_page_test.dart
Labels: size/M

#1581 feat: Update firestore security rules of project groups collection
  metrics/firebase/firestore/rules/firestore.rules
  metrics/firebase/test/firestore/rules/project-groups-test.js
  metrics/firebase/test/firestore/rules/test_utils/test-data.js
Labels: size/L
